redux-form/redux-form

README.md
=> Fixed arguments documentation

src/reduxForm.js
=> Fixed typo, because I'm stupid

src/reduxForm.js
A use case 
https://github.com/erikras/redux-form/issues/23
=> make `handleChange` and `handleBlur` 's input value more flexible

.eslintignore, package.json, scripts/browser, scripts/build, scripts/clean, scripts/lint, scripts/prepublish, webpack.config.base.js, webpack.config.development.js, webpack.config.production.js
Hi Erik!  Your package will now happily build in Windows.  Developer's unite!  I played a part in this for @gaearon and the Redux project.
=> script build windows compatibility

src/reduxForm.js
A minor tweak that'll assist users who upgrade from earlier versions.
=> Improve fields error message to smooth the upgrade path

README.md
Hi, me again, not tested, but I think it should be 'contact' instead of 'contactForm' here right?
=> Fix initialize in example

src/reduxForm.js
=> Fix async validation checking on submit to fix #75

src/reduxForm.js
To fix #77.
Like this, @mattiamanzati?
=> Support for React Native TextInput

src/reduxForm.js
To address #71.
How's this, @BBB?
=> Support for file inputs with event.target.files

package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated redux to version 3.0.1

package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated expect to version 1.11.1

package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated redux to version 3.0.2

src/createAll.js
See https://github.com/erikras/redux-form/pull/139
=> add missing modifications for destroy.

src/createReduxForm.js
Fixes #159 
Another approach would be change the initial value of the reduce function to false, but I wasn't sure how that would sit with the rest of the code
=> Fix issue where empty err object fails validation

README.md, package.json
Rectified example for calculating the `props` from Form Data
=> Calculated props documentation fix

src/pages/App.js
From `react-redux-universal-hot-example` to `redux-form`
=> Fix github link

README.md
I thought the documentation was yet to be written because of the h2 styling of the links…
=> Make it clear that the documentation is linked

src/pages/GettingStarted.md
changed `props` to `this.props` in ContactForm's component example
=> Update GettingStarted.md example

src/pages/api/Reducer.md, src/pages/api/ReducerNormalize.md
This PR updates the docs to match the changes made in https://github.com/erikras/redux-form/commit/e34d1a49ec5a8ca160283e44ab450f767910c0c7
=> update documentation for reducer.normalize

src/__tests__/reducer.spec.js, src/reducer.js
=> Fix reducer getValues and add a test for it

src/__tests__/createReduxForm.spec.js
...when passed directly to `handleSubmit`.
Cheers, Erik - enjoying setting up redux-form on a new project.
=> Tests for submit function being called

src/__tests__/actions.spec.js, src/__tests__/asyncValidation.spec.js, src/__tests__/reducer.spec.js, src/actions.js, src/asyncValidation.js, src/createHigherOrderComponent.js, src/reducer.js
Based on your comments I've changed the code. Please have a look. To show loading icon you could write:
```
asyncValidating === field.name ? <i className="fa fa-spinner fa-spin fa-2x"></i> : null;
```
=> Save field name as asyncValidating prop

src/createHigherOrderComponent.js, src/createReduxForm.js, src/createReduxFormConnector.js
Fixes #326 
Didn't add a test as we're not doing anything with them other than pass them along
Docs PR: #526
=> Pass along mergeProps and options to connect-call

src/pages/faq/ReactNative.md
add react-native integration instructions on github page faq
=> add RN integration instructions on faq

index.html
The current `Loading...` text on the website doesn't look good.
This makes it pretty, like [this one](https://msafi.github.io/string-pattern/), which is copied from the bottom right spinner [here](http://projects.lukehaas.me/css-loaders/).
=> Make spinner pretty

src/__tests__/actions.spec.js, src/__tests__/createReduxForm.spec.js, src/__tests__/readField.spec.js, src/actions.js, src/readField.js, src/reducer.js
Potential fix for #468 
It forces the user to specify the shape of the value being passed into `addField`. But at least it allows me to use redux-form on my project!
=> Potential fix for #468

src/__tests__/createReduxForm.spec.js, src/readField.js
I forgot to deal with the other descending readField() case. This adds a test and fix for that case. Thanks @stevengoldberg for the test case.
=> Fix for #630

src/examples/DynamicFormContainer.js
Filter is definitely easier to read here, and probably more idiomatic.
=> Readability: replace reduce with filter

4.2.0/package.json
I had to reopen the docs to determine which task I should run. Suggest adding a start task that either delegates to dev task or replaces it. Should help avoid confusion for others.
=> Added start task since it's the expected standard.

docs/api/Props.md, docs/api/ReduxForm.md, examples/asyncValidation/src/AsyncValidation.md, examples/simple/src/Simple.md, examples/submitValidation/src/SubmitValidation.md
This will fix dead links documentation website.
=> Fixing dead links in docs

docs/api/ActionCreators.md, docs/api/Props.md, src/__tests__/actions.spec.js, src/__tests__/createReduxForm.spec.js, src/__tests__/reducer.spec.js, src/actionTypes.js, src/actions.js, src/createAll.js, src/createHigherOrderComponent.js, src/createPropTypes.js, src/index.js, src/native.js, src/readField.js, src/reducer.js, src/updateField.js
As we discussed. I tried it out in my app, and it works well.
=> Add autofill action and autofilled field property. #848

examples/README.md, examples/material-ui/.babelrc, examples/material-ui/README.md, examples/material-ui/devServer.js, examples/material-ui/index.html, examples/material-ui/package.json, examples/material-ui/src/MaterialUi.md, examples/material-ui/src/MaterialUiForm.js, examples/material-ui/src/index.js, examples/material-ui/webpack.config.dev.js, examples/material-ui/webpack.config.prod.js
@erikras  
As discussed I have tried to put things in following way.
- Added simple form for material-ui example , I will try to add more.
Things I have observed. 
- With material-ui it is difficult to use as stateless components.
- For for some controls like ``SelectField`` we are treating as custom Component and we are firing onChange manually. Please let me know if there could be better way.
=> Adding Material-ui Examples

src/setErrors.js
introduced in react native by #886
=> fixes Can't find variable: File error

examples/material-ui/src/MaterialUi.md, examples/material-ui/src/MaterialUiForm.js, examples/material-ui/src/asyncValidate.js, examples/material-ui/src/index.js
This will add sync validation and async validation for email
@erikras  I am still trying to find root cause for Webpack being slow.
=> Adding validation under material-ui

src/__tests__/reducer.change.spec.js, src/reducer.js
@erikras I think this addresses the issue in https://github.com/erikras/redux-form/issues/879 while still maintaining the pristine behavior.
=> Support setting a field that has been initialized to ""

src/__tests__/reducer.blur.spec.js, src/reducer.js
@erikras we also need to adjust the blur behavior
=> Make sure we don't delete the value on blur either

src/reduxForm.js
Reverts erikras/redux-form#947
=> Revert "Potential hot destroy fix"

docs/faq/CustomComponent.md, docs/faq/EnterToSubmit.md, docs/faq/ImmutableJs.md, docs/faq/README.md
Just a few small things I spotted while reading the FAQ.
=> Fix several FAQ typos

src/__tests__/setup.js
See #971 
See https://github.com/tmpvar/jsdom/commit/306805ad7dd8435b868ed95ae699116346201d06
=> v6 — Fix navigator

examples/asyncValidation/package.json, examples/fieldArrays/package.json, examples/immutable/package.json, examples/initializeFromState/package.json, examples/material-ui/package.json, examples/selectingFormValues/package.json, examples/simple/package.json, examples/submitValidation/package.json, examples/syncValidation/package.json, examples/wizard/package.json
=> v6 — Use local redux-form

src/Field.js, src/FieldArray.js
This reverts commit b1e258bdf11b04e633f0852b15ab6005c818a456.
See https://github.com/erikras/redux-form/issues/961#issuecomment-219785684 and https://github.com/erikras/redux-form/issues/961#issuecomment-219826459
=> Revert "found focus-loss rerender bug."

CHANGELOG.md, CONTRIBUTING.md
See #884
The following guidelines are mainly taken from Redux's ones and are far from perfect. Unfortunately I'm not enough comfortable with English to write something _good_.
If you have suggestions, corrections or anything to add, feel free to commit here. If you want to add substantial changes to this PR, you can submit a PR on the `gh_docs` branch.
=> Add contribution guidelines

src/__tests__/reducer.spec.js, src/reducer.js
This PR adds a test to demonstrate the issue exposed in https://github.com/erikras/redux-form/issues/1001#issuecomment-220128834.
It also fixes the issue #1001.
**DO NOT MERGE if this is the expected behavior!**
**DO NOT MERGE if we consider this bug as a _feature_ because it lives for too long!**
=> blur should do anything if it does not target the active field

src/__tests__/reducer.blur.spec.js, src/reducer.js
This the v6 implementation of #1002
=> blur should not change active field if the blurred field is not active

src/__tests__/immutable.spec.js, src/__tests__/index.spec.js, src/__tests__/values.spec.js, src/immutable.js, src/index.js, src/values.js
=> Added missing action creator exports and tests

docs/api/Props.md
=> Mention SubmissionError in onSubmit docs

docs/api/Field.md, examples/asyncValidation/package.json, examples/asyncValidation/src/AsyncValidationForm.js, examples/fieldArrays/package.json, examples/fieldArrays/src/FieldArrays.md, examples/fieldArrays/src/FieldArraysForm.js, examples/immutable/package.json, examples/immutable/src/ImmutableForm.js, examples/immutable/src/ImmutableValues.js, examples/immutable/src/index.js, examples/initializeFromState/package.json, examples/material-ui/index.html, examples/material-ui/package.json, examples/material-ui/src/MaterialUi.md, examples/material-ui/src/MaterialUiForm.js, examples/material-ui/src/index.js, examples/selectingFormValues/package.json, examples/simple/package.json, examples/submitValidation/package.json, examples/submitValidation/src/SubmitValidationForm.js, examples/syncValidation/package.json, examples/syncValidation/src/SyncValidation.md, examples/syncValidation/src/SyncValidationForm.js, examples/wizard/package.json, examples/wizard/src/Wizard.md, examples/wizard/src/WizardFormFirstPage.js, examples/wizard/src/WizardFormSecondPage.js, examples/wizard/src/WizardFormThirdPage.js, examples/wizard/src/index.js, examples/wizard/src/renderField.js
Addresses decision made after discussion in #961.
=> Update examples to avoid fat arrow component creation in render()

src/__tests__/createReduxForm.spec.js, src/__tests__/readField.spec.js, src/__tests__/readFields.spec.js, src/readField.js
=> Ensure initial values are present on first render

docs/api/FieldArray.md, examples/fieldArrays/src/FieldArraysForm.js, src/ConnectedField.js, src/__tests__/Field.spec.js, src/__tests__/FieldArray.spec.js, src/__tests__/createFieldArrayProps.spec.js, src/createFieldArrayProps.js
=> Separate field array props

docs/api/ReduxForm.md, src/__tests__/reduxForm.spec.js, src/reduxForm.js
=> Provide wrapped ref for testing. #1081

src/__tests__/handleSubmit.spec.js, src/__tests__/reduxForm.spec.js, src/handleSubmit.js
=> Touch all on submit

docs/api/Field.md, examples/normalizing/.babelrc, examples/normalizing/README.md, examples/normalizing/devServer.js, examples/normalizing/index.html, examples/normalizing/package.json, examples/normalizing/src/FieldNormalizing.md, examples/normalizing/src/FieldNormalizingForm.js, examples/normalizing/src/index.js, examples/normalizing/src/normalizePhone.js, examples/normalizing/webpack.config.dev.js, examples/normalizing/webpack.config.prod.js, src/ConnectedField.js, src/Field.js, src/__tests__/Field.spec.js, src/__tests__/createFieldProps.spec.js, src/createFieldProps.js, src/events/__tests__/createOnBlur.spec.js, src/events/__tests__/createOnChange.spec.js, src/events/createOnBlur.js, src/events/createOnChange.js, src/reduxForm.js
This accomplishes _most_ of what the `v5` [`reducer.normalize()`](http://redux-form.com/5.2.5/#/api/reducer/normalize) API was providing.
=> Added normalize prop to Field

docs/GettingStarted.md, docs/faq/EnterToSubmit.md
http://webaim.org/techniques/forms/controls
=> Make form examples more accessible

docs/api/ReduxForm.md, src/__tests__/reduxForm.spec.js, src/reduxForm.js
Addresses #1084.
See also #832.
=> Added enableReinitialize config flag

src/__tests__/createReduxForm.spec.js, src/readFields.js
Reverts erikras/redux-form#1061. As requested on #1244.
=> Revert "Pass initial values to validate function on first render"

docs/api/ReduxForm.md, src/__tests__/reduxForm.spec.js, src/asyncValidation.js, src/handleSubmit.js, src/reduxForm.js
Existed on `v5`, but was not yet implemented on `v6`. #853
=> Added onSubmitSuccess and onSubmitFail

src/__tests__/createFieldProps.spec.js, src/createFieldProps.js
=> Fix file input

docs/MigrationGuide.md, docs/api/Field.md, examples/asyncValidation/src/AsyncValidationForm.js, examples/fieldArrays/src/FieldArraysForm.js, examples/immutable/src/ImmutableForm.js, examples/material-ui/src/MaterialUiForm.js, examples/react-widgets/src/ReactWidgetsForm.js, examples/submitValidation/src/SubmitValidationForm.js, examples/syncValidation/src/SyncValidationForm.js, examples/wizard/src/WizardFormThirdPage.js, examples/wizard/src/renderField.js, package.json, src/ConnectedField.js, src/__tests__/Field.spec.js, src/__tests__/FieldArray.spec.js, src/__tests__/createFieldProps.spec.js, src/__tests__/handleSubmit.spec.js, src/__tests__/reduxForm.spec.js, src/createFieldProps.js, src/handleSubmit.js
As discussed on #1249.
This will be a Breaking Change, but there's nothing we can really do about it.
=> [React 15.2.0] Moved input props to input structure

docs/GettingStarted.md
This would have been very helpful for me to know up front.  I spent like 6 hours trying to figure out how to 'bind' redux data to the form because I didn't understand that you could trigger form behavior from external components.
In my case, I have a modal window for Terms and Conditions which can either check or uncheck a checkbox.
=> Add Action Creators to the primary contents in the getting started guide

examples/asyncValidation/index.html, examples/asyncValidation/src/index.js, examples/fieldArrays/index.html, examples/fieldArrays/src/index.js, examples/immutable/index.html, examples/immutable/src/index.js, examples/initializeFromState/index.html, examples/initializeFromState/src/InitializeFromState.md, examples/initializeFromState/src/index.js, examples/material-ui/index.html, examples/material-ui/src/index.js, examples/normalizing/index.html, examples/normalizing/src/index.js, examples/react-widgets/index.html, examples/react-widgets/src/index.js, examples/selectingFormValues/index.html, examples/selectingFormValues/src/index.js, examples/simple/index.html, examples/simple/src/index.js, examples/submitValidation/index.html, examples/submitValidation/src/index.js, examples/syncValidation/index.html, examples/syncValidation/src/index.js, examples/wizard/index.html, examples/wizard/src/index.js
Bump rc version in examples to fix menu links.
Fixed typo in word "values" at InitializeFromState readme
=> Bump rc version in examples to fix menu links

docs/api/ReduxForm.md
Just noticed it comparing documentation to a logged value.
=> Small doc update registeredFields - I believe this field has changed I don't know when it changed

package.json, src/reducer.js
=> Array.findIndex() polyfill

src/events/__tests__/getValue.spec.js, src/events/getValue.js
=> event with value key shouldnt be special case

src/__tests__/createReduxForm.spec.js, src/__tests__/handleSubmit.spec.js, src/handleSubmit.js
=> pass props to `handleSubmit()` function

src/propTypes.js
=> Fixes propTypes export

src/__tests__/reduxForm.spec.js, src/reduxForm.js
=> Fixed remount-reinitialize bug

src/__tests__/reducer.updateSyncErrors.spec.js, src/__tests__/reduxForm.spec.js, src/reducer.js
=> Fix sync form wide error

src/Field.js, src/__tests__/Field.spec.js
=> Reregistered fields when name prop changes

docs/api/Props.md, src/__tests__/reduxForm.spec.js, src/propTypes.js, src/reduxForm.js
No reason _not_ to provide these.
Addresses #1579.
=> Replaced blur and change bound actions as form props

docs/api/Field.md, examples/react-widgets/src/ReactWidgets.md, examples/react-widgets/src/ReactWidgetsForm.js, src/ConnectedField.js, src/ConnectedFieldArray.js, src/ConnectedFields.js, src/Field.js, src/Fields.js, src/__tests__/createFieldProps.spec.js, src/createFieldProps.js
RIP `defaultValue`. It was causing too much confusion. Addresses #1341.
=> Nixed defaultValue 👻

src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js, src/__tests__/createFieldArrayProps.spec.js, src/createFieldArrayProps.js
=> Fixed bug where FieldArray would not rerender on add/remove

docs/api/Props.md, src/__tests__/reduxForm.spec.js, src/reduxForm.js
=> Passthrough the initialValues prop to the enhanced component.

docs/MigrationGuide.md
=> #1635 Replacing duplicated username with password in V6 example

src/__tests__/reducer.change.spec.js, src/__tests__/reduxForm.spec.js, src/reducer.js
=> fix submit form after failing

package.json
https://github.com/erikras/redux-form/issues/1513
https://github.com/bjyoungblood/es6-error/issues/22
https://github.com/mxstbr/react-boilerplate/pull/551
=> update es6-error version

src/__tests__/reduxForm.spec.js, src/reduxForm.js
=> Bound change and blur to dispatch

src/events/__tests__/getValue.spec.js, src/events/getValue.js
Aims to resolve issue #1438 
Added code to handle radio buttons and added relevant unit tests.
=> Correctly handle tabbing over radio buttons

docs/api/Reducer.md
Just got bitten. Think it should be added to documentation.
=> With Immutablejs, reducer must come from 'redux-form/immutable'

src/__tests__/reducer.setSubmitSuceeded.spec.js, src/__tests__/reduxForm.spec.js, src/reducer.js
This fixes https://github.com/erikras/redux-form/issues/1688. I added a test case that was failing previously for sync onSubmit and added a test case for Promise onSubmit.
=> Changed setSubmitSucceeded to not touch submitting state

src/reduxForm.js
=> Fixed double change dispatch

src/ConnectedField.js, src/ConnectedFieldArray.js, src/ConnectedFields.js
=> Fixes #1785. Ensures component is updated if props length changes.

src/__tests__/reducer.change.spec.js, src/__tests__/reducer.updateSyncErrors.spec.js, src/__tests__/reduxForm.spec.js, src/reducer.js, src/selectors/__tests__/isInvalid.spec.js, src/selectors/__tests__/isValid.spec.js, src/selectors/isValid.js
fix #1819 sync validation errors flicker on changing
=> fix sync validation errors flicker on changing

src/__tests__/createFieldArrayProps.spec.js, src/createFieldArrayProps.js
=> Add name to FieldArray props that get passed down under fields

docs/GettingStarted.md, examples/asyncValidation/src/AsyncValidation.md, examples/simple/src/Simple.md, examples/submitValidation/src/SubmitValidation.md
- Fixed some broken links in the examples section.
- Clarified GettingStarted example, to prevent Issue #190 for new users.
=> Documentation updates

docs/api/Props.md
=> Removed duplicate "are" in docs

src/__tests__/reducer.updateSyncErrors.spec.js, src/reducer.js, src/selectors/__tests__/isInvalid.spec.js, src/selectors/__tests__/isValid.spec.js, src/selectors/isValid.js
=> Fix sync validation

src/__tests__/handleSubmit.spec.js, src/handleSubmit.js
I've changed the code in a way that preserves changes from #1843 
Fix #1929
=> Make handleSubmit doesn't submit when asyncValidation fails

examples/fieldArrays/src/validate.js
Change `forEach` to `map`, otherwise `return memberErrors` does not make sense.
Edit: Remove return statement
=> [Docs] Update validate.js

docs/api/Selectors.md, src/createAll.js, src/index.js, src/selectors/__tests__/getFormSubmitErrors.spec.js, src/selectors/getFormSubmitErrors.js
See https://github.com/erikras/redux-form/issues/2069
=> Added getFormSubmitErrors selector

src/__tests__/reducer.blur.spec.js, src/__tests__/reducer.change.spec.js, src/reducer.js
This change caused problems. Fixes #1993.
=> Revert "fix checkox behavior"

src/__tests__/reduxForm.spec.js, src/reduxForm.js
=> Values passed to the sync validation function must be defined

src/__tests__/reducer.initialize.spec.js, src/reducer.js
=> Persist warnings through the initialize() action.

examples/README.md, examples/asyncValidation/README.md
Just noticed a little typo, small ways for us to give back :)
=> Fix typos "aynchronous" -> "asynchronous"

docs/api/Field.md, docs/api/Fields.md, src/__tests__/createFieldProps.spec.js, src/createFieldProps.js
=> Allow null to empty string conversion override using format

src/FormSection.js, src/__tests__/FormSection.spec.js
I don't want extra `div`s in my DOM 😄
=> Only wrap FormSection in a div if necessary

docs/api/FieldArray.md
=> [Docs] Fixed a duplicate periods in `docs/api/FieldArray.md`

docs/api/Form.md, examples/remoteSubmit/src/RemoteSubmitForm.js, src/Form.js, src/__tests__/Form.spec.js, src/createAll.js, src/handleSubmit.js, src/immutable.js, src/index.js, src/reduxForm.js
Fixes #2238. Based on https://github.com/erikras/redux-form/issues/2238#issuecomment-268641999 from @davidkpiano.
=> Created Form component

package.json
Reference: c790172c5
Fixes #2330
=> Add back caret prefix to react and redux versions

src/__tests__/Field.spec.js, src/createFieldProps.js
=> Cleaned up some prop leakage

src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js, src/__tests__/createFieldArrayProps.spec.js, src/createFieldArrayProps.js
=> Fixed bug with FieldArray fields.get()

src/FieldArray.js, src/__tests__/FieldArray.spec.js
=> Allowed for an array of validators to FieldArray

examples/asyncValidation/index.html, examples/fieldArrays/index.html, examples/fieldLevelValidation/index.html, examples/immutable/index.html, examples/initializeFromState/index.html, examples/material-ui/index.html, examples/normalizing/index.html, examples/react-widgets/index.html, examples/remoteSubmit/index.html, examples/selectingFormValues/index.html, examples/simple/index.html, examples/submitValidation/index.html, examples/syncValidation/index.html, examples/wizard/index.html
=> Set proper <title> tag to examples

src/reduxForm.js
=> Avoided unnecessary deepEqual() for pristine

examples/initializeFromState/src/InitializeFromStateForm.js, package.json, src/reducer.js
Silly to use this for just one loop.
Fixes #2337.
=> Removed array-findindex-polyfill

src/ConnectedFields.js, src/Fields.js, src/__tests__/Fields.spec.js
Fixes bug introduced by #2161.
=> Update ConnectedFields cached handlers when names prop changes.

.codeclimate.yml, src/__tests__/index.spec.js, src/createAll.js, src/immutable.js, src/index.js
=> Exported getFormNames

.github/issue_template.md
Hopefully this will enable people to create more useful issues.
=> Create basic issue template

src/__tests__/FieldArray.spec.js, src/reduxForm.js
=> Avoided unnecessary call to sync validation

examples/fieldArrays/src/FieldArraysForm.js, src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js, src/createFieldArrayProps.js
=> Added submitFailed to FieldArray meta prop

src/propTypes.js
This adds some missing propTypes to the ones that get passed to your decorated form component.
=> Add missing propTypes

docs/GettingStarted.md, docs/faq/HowToConnect.md, docs/faq/README.md
@gustavohenke here's a PR for #1050
=> Docs update

src/ConnectedField.js, src/__tests__/Field.spec.js
This is a fix for the issue: #2647.
=> Fix #2647 ("pristine" not calculated using deep equality)

docs/faq/ReactNative.md
=> Replace React Native FAQ

src/__tests__/reducer.untouch.spec.js, src/reducer.js
=> Fixed anyTouched bug on UNTOUCH

docs/api/FieldArray.md, src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js, src/__tests__/createFieldArrayProps.spec.js, src/createFieldArrayProps.js
=> Added meta.form to FieldArray props

src/FieldArray.js, src/generateValidator.js
As suggested by @jerrysu on #2720.
=> Replaced usages of for...of construct for stupid IE

examples/fieldArrays/src/FieldArraysForm.js
Found by codeclimate.
I just switched the two method definitions.
=> Fix 'renderHobbies' was used before it was defined eslint error

src/propTypes.js
fix https://github.com/erikras/redux-form/pull/2707 problems
Fixes #2744
=> Fix triggerSubmit/clearSubmit propTypes problems

src/ConnectedField.js, src/ConnectedFieldArray.js, src/ConnectedFields.js, src/__tests__/Field.spec.js, src/__tests__/FieldArray.spec.js, src/__tests__/reducer.arrayRemove.spec.js, src/__tests__/reducer.updateSyncErrors.spec.js, src/reducer.js, src/structure/immutable/index.js, src/structure/plain/index.js
=> Fixed inconsistent treatment of sync errors in redux-form/immutable

src/ConnectedFields.js, src/__tests__/Fields.spec.js
meta.form is undefined for `Fields` component. This pr adds the failing test case and the fix.
=> pass meta.form to Fields component

src/__tests__/reduxForm.spec.js, src/reduxForm.js
=> Enable initialize in componentWillMount()

package.json, src/__tests__/createReduxForm.spec.js, src/createAll.js, src/createHigherOrderComponent.js, src/createPropTypes.js, src/createReduxFormConnector.js
=> Migrated to v5 to prop-types

package.json
I guess this does not affect anything in any inappropriate way
=> clean script - added es folder to be rimrafed before build

src/__tests__/reducer.unregisterField.spec.js, src/reducer.js
Cleaned up the following on field unregister:
- sync errors
- sync warnings
- submit errors
- async errors
Fixes #2884.
=> Better cleanup on UNREGISTER

README.md
See https://github.com/prettier/prettier#badge
=> Update README.md - Add Prettier Badge

docs/faq/BundleSize.md
=> Clarify documentation for reducing redux-form size

docs/api/FormSection.md
=> Correct typo in FormSection docs

docs/api/FormValueSelector.md
=> Remove redundant example from formValueSelector docs

docs/api/FieldArray.md, src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js
#3008 
1. Added `rerenderOnEveryChange` prop to `FieldArray`
2. Added test `should rerender when a value changes if rerenderOnEveryChange setted`
3. Added docs for `rerenderOnEveryChange`
=> Added rerenderOnEveryChange

examples/immutable/src/index.js, examples/immutable/src/warn.js
Continuation of #3042. My copy pasta skills weren't adequate, and I wasn't able to verify the code live. Sorry! Also, imported the raw code file in the markdown file as well.
=> Fix small mistakes with Immutable `warn` demo

docs/api/ReducerPlugin.md
Hi I just started explore redux-form, maybe I wrong but I think there is an error in a key name.
=> fix Form instance key name

examples/syncValidation/src/SyncValidation.md
Mention [current behavior](https://github.com/erikras/redux-form/issues/2988).
=> Update syncValidation with info about errors

src/components/Markdown.js, src/components/Markdown.scss
=> Docs: Add anchors to each heading

.npmignore
Fix for https://github.com/erikras/redux-form/issues/2842 and https://github.com/erikras/redux-form/issues/3131
=> Ignore lock files

src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js
#3008 
1. Fixed behavior in `shouldComponentUpdate` method of `ConnectedFieldArray`
2. Added test `should rerender when a value changes if rerenderOnEveryChange is set and FieldArray has multiple groups with same values`
=> Fixed rerenderOnEveryChange for FieldArray with same groups (#3008)

src/structure/plain/__tests__/deepEqual.spec.js, src/structure/plain/deepEqual.js
Addresses #3061, #1762, #1774, and #1993.
=> BC: Treat undefined and false as NOT equal

docs/api/ReduxForm.md, examples/asyncValidation/src/AsyncValidation.md
Resolves documentation issue: https://github.com/erikras/redux-form/issues/3058
=> Update docs for asyncBlurFields

docs/api/Fields.md
=> Docs: emphasize the nature of Fields vs Field

src/ConnectedFields.js, src/__tests__/Fields.spec.js
fieldProps.meta.initial was not being set for Fields components.
=> Add missing initial prop to Fields

src/createField.js
Fixes #3172.
#3201 broke this.
=> Fixed field-level validation bug

src/immutable.js.flow, src/index.js.flow
Fixes #3175.
...or so I hope...
=> Exported flow types for HOC props

src/createFormValues.js
This fixes the problem described in #3202
=> Fixed context not up to date in createFormValues

src/components/Markdown.js, src/components/Markdown.scss
Fix for https://github.com/erikras/redux-form/pull/3076#issuecomment-315911338
I didn't test it, but I have trust this won't make things any worse 😅
=> Docs: don't hide non-anchor links in headings

docs/api/FormValueSelector.md
Inspired by #1699. I remember I was initially confused too on first read. I think this makes the sentence subject formValuesSelector more explicit when mentioning the concept of a selector api.
=> Clarify formValueSelector docs intro

package-lock.json, package.json, src/FieldProps.types.js.flow, src/createFieldProps.js, src/createReduxForm.js, src/handleSubmit.js, src/immutable.js.flow, src/index.js.flow
=> Flow fixes

docs/api/Selectors.md
=> Docs: getFormNames fixup

docs/api/ActionCreators.md
Relates to PR: #2615 (for #2604)
Will help with #2599, #2895
=> Document missing action creators

src/FieldProps.types.js.flow
- Update InputProps onBlur and onChange to match API docs
<http://redux-form.com/7.0.3/docs/api/Field.md/#-code-input-onblur-eventorvalue-function-code->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/erikras/redux-form/3324)
=> fix(flowtype) InputProps onBlur and onChange

src/ConnectedFieldArray.js, src/__tests__/FieldArray.spec.js
I Added test for FieldArray fields.swap method because it looked that it was not working. 
After running tests this one indeed failed so I updated shouldComponentUpdate method of ConnectedFieldArray so that it returns true if some elements in array were swapped.
Can someone confirm if the test is correct? Possibly change it if needed. I think some expect calls might be unnecessary.
Is the shouldComponentUpdate solution acceptable?
=> FieldArray swap does not rerender

docs/api/ReduxForm.md
It's not the first time this problem in the docs is raised.
This reverts commit fa645249397d65650b88b02b1c8802ef5dc122da/PR #1404.
Fixes #3396
=> Revert fieldList/registeredFields instance API docs

docs/faq/ButtonType.md, docs/faq/README.md
=> Add button `type` gotcha to FAQ

docs/faq/HandleVsOn.md
=> Remove incorrect information from FAQ/HandleVsOn.md

.babelrc, package.json, src/__tests__/Fields.spec.js
Added a babel plugin to help track down React 16 warnings. Found via https://github.com/facebook/react/issues/11083.
=> Fixed some React 16 warnings

src/__tests__/reduxForm.spec.js, src/structure/immutable/__tests__/deepEqual.spec.js, src/structure/immutable/deepEqual.js, src/structure/plain/__tests__/deepEqual.spec.js
Fixes #3357.
Not the first time ignoring an eslint error created a bug. 🤦‍♂️
=> Changed immutable/deepEqual to use ===

src/ConnectedField.js, src/ConnectedFieldArray.js, src/ConnectedFields.js, src/createReduxForm.js
=> React16: Prevented deepEqual checks on props.children in shouldComponentUpdate()

src/structure/plain/__tests__/deepEqual.spec.js, src/structure/plain/deepEqual.js
Credit to @umidbekkarimov for the idea. 👍  https://github.com/erikras/redux-form/issues/3461#issuecomment-334432363
=> Added React.isValidElement() check in deepEqual()

src/__tests__/reduxForm.spec.js, src/events/__tests__/getValue.spec.js, src/events/getValue.js
Fixes #2857, #2922, #3162, #3437.
=> Fixed broken checkbox behavior

src/__tests__/defaultShouldError.spec.js, src/__tests__/defaultShouldWarn.spec.js, src/__tests__/immutable.spec.js, src/__tests__/index.spec.js, src/__tests__/reduxForm.spec.js, src/createReduxForm.js, src/defaultShouldError.js, src/defaultShouldWarn.js, src/immutable.js, src/immutable.js.flow, src/index.js, src/index.js.flow
This is an initial implementation for the feature requested in https://github.com/erikras/redux-form/issues/3449
=> Separate error and warnings in validation override

docs/api/ReduxForm.md, src/createReduxForm.js
Also provided docs for #3464's `shouldError()` and `shouldWarn()`.
=> Deprecated shouldValidate

src/__tests__/helpers/reducer.plugin.js, src/createReducer.js, src/structure/plain/__tests__/deepEqual.spec.js
=> Fixed plugin bug demonstrated in #2935

src/__tests__/helpers/reducer.plugin.js, src/createReducer.js
=> Fixed reducer plugin bug introduced in v7.1.0

src/ConnectedFieldArray.js
=> Replaced includes with indexOf

src/createReduxForm.js
=> Pass destroyOnUnmount as second parameter when unregistering form fields

src/__tests__/reduxForm.spec.js, src/createReduxForm.js
This should fix https://github.com/erikras/redux-form/issues/3529
=> Add `array` to propNamespace

docs/api/Field.md
Made it more clear in the docs that complicating name prop in the Field component is also a string
=> A bit clearer docs

src/actions.js, src/actions.types.js.flow
=> Added optional type definitions for Change action type

src/__tests__/formValues.spec.js, src/createFormValues.js, src/formValues.types.js.flow
=> Fix for formValues not reacting to props change

src/ConnectedFieldArray.js, src/ConnectedFields.js, src/__tests__/FieldArray.spec.js, src/__tests__/FormSection.spec.js
Reverts erikras/redux-form#3802
=> Revert "Fix flat structure for asyncErrors and submitErrors for FieldArray and Fields."

src/__tests__/reduxForm.spec.js, src/createReduxForm.js
Duplicate of #3797, which accidentally got reverted.
=> Fix for double INITIALIZE happening on first mount (AGAIN)

src/__tests__/formValues.spec.js, src/createFormValues.js, src/formValues.types.js.flow
Duplicate of #3794, which accidentally got reverted.
=> Fix for formValues not reacting to props change (AGAIN)

docs/api/ReduxForm.md, examples/README.md, examples/asyncChangeValidation/.babelrc, examples/asyncChangeValidation/.eslintrc, examples/asyncChangeValidation/README.md, examples/asyncChangeValidation/devServer.js, examples/asyncChangeValidation/index.html, examples/asyncChangeValidation/package-lock.json, examples/asyncChangeValidation/package.json, examples/asyncChangeValidation/src/AsyncValidation.md, examples/asyncChangeValidation/src/AsyncValidationForm.js, examples/asyncChangeValidation/src/asyncValidate.js, examples/asyncChangeValidation/src/index.js, examples/asyncChangeValidation/src/reducer.js, examples/asyncChangeValidation/src/validate.js, examples/asyncChangeValidation/webpack.config.dev.js, examples/asyncChangeValidation/webpack.config.prod.js
After this PR https://github.com/erikras/redux-form/pull/3531 there is new option in redux-form.
I added info about it to the docs.
Interesting thing about default values for `shouldAsyncValidate` option:
- In the PR there were two cases: `blur` and `change`
https://github.com/ericbiewener/redux-form/blob/270ea7b1114ff57cbb74e3bdf0faac4ccc575b3f/src/defaultShouldAsyncValidate.js#L22
- In master there is only `blur` case
https://github.com/ericbiewener/redux-form/blob/master/src/defaultShouldAsyncValidate.js#L21
Maybe it will be more clear to change key from `blurredField` to `changedField` there
https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L718
=> Add info about asyncChangeFields to docs

docs/api/ReduxForm.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/erikras/redux-form/3871)
=> Fix link to Asynchronous Change Validation Example

examples/material-ui/package-lock.json, examples/material-ui/package.json
The lock file increased substantially so if it's ugly to your eyes, let me know and I can just include the package.json. Cheers!
=> Fix babel-loader package version from 7.2.3 to the latest current, which is 7.1.2

package.json
Redux 4 is out: https://github.com/reactjs/redux/releases/tag/v4.0.0
I didn't notice any breaking changes. 💯
This is small and clear PR, hope I didn't miss anything.
=> Add support for redux 4.x

package.json
I know that v5 is old but still a lot of people use it and it would be nice to allow them to use redux 4. 😃
=> Allow redux 4 (v5)

src/asyncValidation.js
=> Async validation improvements

src/structure/immutable/__tests__/setIn.spec.js, src/structure/immutable/setIn.js
=> fixes 'invalid keyPath' when loading initial values (#3943)

src/deleteInWithCleanUp.js
=> Fix clear errors in parent of array after child change

src/deleteInWithCleanUp.js
Reverts erikras/redux-form#4014
This broke a ton of tests.
=> Revert "Fix clear errors in parent of array after child change"

src/__tests__/reduxForm.spec.js, src/createReduxForm.js
=> Feat: add keepValues to form config

src/handleSubmit.js
Fixes https://github.com/erikras/redux-form/issues/4094.
=> Fix handleSubmit with redux-form/immutable

src/types.js.flow
Change type of asyncValidating from `boolean` to `boolean | string`
=> Fix FormProps#asyncValidating type

src/FormName.js
do you guys think it's reasonable to include `sectionPrefix` here?
=> feat(FormName): also pass sectionPrefix

docs/MigrationGuide.md
Fixing a few grammatical errors.
=> Fixing a few grammatical errors

package-lock.json, package.json
Version 4.17.10 has a vulnerability
https://hackerone.com/reports/380873
=> Update lodash to 4.17.11

src/handleSubmit.js
This PR improves the effort made in https://github.com/erikras/redux-form/pull/4095.
=> Remove dependency from Immutable

src/ConnectedField.js
Fixes [#3446](https://github.com/erikras/redux-form/issues/3446)
=> Fix ConnectedField to accept values that isn't React SyntheticEvent (#3446)

package.json
=> Fix build: ignore __tests__ directories in "es" and "lib" (#4325)

src/handleSubmit.js
Following fix suggested here: https://github.com/erikras/redux-form/issues/4302#issuecomment-448998142
Fixes #4302, maybe.
=> Changed how isSubmissionError works due to Babel 7 change

.babelrc.js, package-lock.json, package.json
=> Add @babel/plugin-transform-runtime (#4324)

src/handleSubmit.js
=> Convert immutable List to array

docs/api/ReducerPlugin.md, src/__tests__/helpers/reducer.plugin.js, src/createReducer.js
One possible solution to: https://github.com/erikras/redux-form/issues/4310
If this seems like something we'd want to do, I can polish up this PR more.
=> Add config for plugins receving actions from all forms

docs/api/FormValueSelector.md
I just fixed a little grammatical error.
=> Update FormValueSelector.md  change "are" for "is" 

docs/api/Field.md, src/FieldProps.types.js.flow
=> FieldInputProps.component redundant definition

src/handleSubmit.js, src/types.js.flow
=> handleSubmit type

.babelrc.js, src/handleSubmit.js
=> Fix immutable support

CONTRIBUTING.md
Can someone please help me fill out the CONTRIBUTING.md so it is actually useful. I'm just getting things started here. 
@erikras @asazernik @showme79 @YunzheZJU @sanex3339 
(you all contributed recently so that's why you're mentioned. Thanks!)
=> adds CONTRIBUTING.md

package-lock.json, package.json
Please see related git issue #4506
=> Upgrade: update lodash - CVE-2019-10744 (fixes #4506)

docs/api/README.md, docs/api/ReduxFormContext.md, src/index.js.flow
=> docs: add ReduxFormContext docs and usage example

docs/api/Props.md
=> Update docs description about change prop

CODE_OF_CONDUCT.md
Email address was approved by repository author, @erikras
=> chore: add Contributor Covenant Code of Conduct

examples/material-ui/src/MaterialUiForm.js
=> fix(examples): change label to reflect input

docs/api/ActionCreators.md, docs/api/Props.md, src/__tests__/helpers/reducer.clearFields.js, src/createReducer.js
where clearFields did not work as expected with initial values
Basically I have copied the logic from resetSection for resetting to initial values
Closes #4101
=> feat(reducer/clear-fields): set to initial values if present, otherwise cleanup

docs/api/Field.md
=> fix(docs): fix `select-multiple` type for `Field`

package.json
https://yarnpkg.com/configuration/manifest#peerDependenciesMeta
=> make immutable an optional dep

.eslintignore, .prettierignore, flow-typed/npm/lodash_v4.x.x.js
Folder `flow-typed` should not be modified by user, it should be managed by `flow-typed`
=> chore: update lodash flow types, prettier ignore flow-typed

.flowconfig, flow-typed/npm/redux_v4.x.x.js, package-lock.json, src/FieldProps.types.js.flow, src/createReduxForm.js, src/types.js.flow
=> refactor(flow): fix flow `untyped-type-import` warnings

package-lock.json, package.json, webpack.config.js
=> chore: remove unused `uglifyjs-webpack-plugin`

src/createFields.js
=> refactor(Fields): remove react legacy string refs

README.md, package-lock.json, package.json
[Reasoning here](https://twitter.com/erikras/status/1278071436754575360).
=> Removed scarf analytics
