src/reduxForm.js

Since we're already using destructuring here, we can skip the 2nd destructuring step and the `delete` (in order to avoid possible deoptimization of the function)

No need for a 2nd destructuring and `delete`

---

src/reduxForm.js

This adds the name of the field to the field object.
I thought it might be good to have the name of the field at hand as well. Especially for custom and more complex input fields that need to implement their own change/blur handlers. Otherwise you would need to pass the field name from the redux form decorated component all the way down to ther pertaining component.
Feel free to close if you think this is not necessary of you want to add it yourself.

Add field name to field object

---

README.md

Just fixed a couple of `&lt;` and some consistency issues.

Fix formatting issues in API docs in readme.md

---

src/util.js

`isPristine` is throwing when value is changing from `null` to object. This is a fix.

null handling in isPristine

---

src/isValid.js
src/reduxForm.js
test/isValid.spec.js

As discussed on Slack, when a field's error property was an array of falsey values the form was deemed invalid.

Allow for a field's errors to be an array.

---

src/reducer.js
test/reducer.spec.js

Attempts to use reducer.normalize as documented would result in the following error:
Uncaught TypeError: Cannot read property 'myField' of undefined
I've some unit tests and a fix that sets initialState in reducer.normalize

Fix for missing initialState in reducer.normalize

---

src/createReduxForm.js

This patch:
• Updates a form's `handleChange()` prop to dispatch if passed both a field and value as stated in documentation. Related issue [#108](https://github.com/erikras/redux-form/issues/108)

Update handleChange to dispatch immediately when passed a value (#108)

---

src/createReduxForm.js

To support server-side rendering, populate `initialValues` using `defaultValue` and `defaultChecked`
I was not ambitious enough to add component tests to add a regression test for this issue.  Hopefully that is okay for now :grin:.
Closes #97
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/erikras/redux-form/132)

Populate `initialValues` on first render

---

package.json

Fix #135 
Now you also have to include `redux` and `react-redux` explicitly when using `redux-form`. This is not an issue since almost every developer will include them. I've also change version requirements to carets since `redux` is strictly following semver.
This PR does not change `redux` or `react` compatibility :wink:

Add redux as peer dependency

---

README.md
src/actionTypes.js
src/actions.js
src/createReduxForm.js
src/index.js
src/reducer.js
test/actions.spec.js
test/reducer.spec.js

for proper memory management with apps that generate a significant amount of dynamic forms.

Allow removal of the whole form object from the reducer

---

README.md

Was linking to how-it-works, which appears to have been removed some time ago.  I think it should be linking to the "simple form component" example instead.

fixed link in README

---

src/isPristine.js
test/isPristine.spec.js

Hey guys! I have a case when initial value of a form's field is an empty array.
After updating the field via `this.props.fields['someField'].handleChange([1, 2, 3])`, `this.props.pristine` remain equal to `true`.
This pull request should fix the problem.

isPristine should return false when the number of keys is different

---

src/createHigherOrderComponent.js

This allows for the `initialValues` property to be in the `mapPropsToValues` form, matching an idiom already familiar to the redux world. This also provides an entry-point in taking advantage of react props in conjuction with a reduxForm.
```
const Form = reduxForm({
initialValues: (props) => ({query: props.query})
});
const RenderedForm => (
<Form field={location.query.query} />
)
```

allow initialValues to be in the `mapPropsToValues` form

---

package.json

See https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module

add a jsnext:main so we can distribute ES2015 modules

---

src/getValues.js
src/readFields.js
src/reducer.js

Spread operators is very slow when there are many fields (I have a 200+ fields huge form).
Compare using spread operators and not: http://jsbin.com/tibiji/edit?js,console

Remove spread operators

---

src/__tests__/createReduxForm.spec.js
src/readFields.js

`readField`'s return value can be an array so in order to determine if a form is dirty, I handle this case by iterating through all the elements.

Set dirty when array field changes

---

.eslintrc
src/__tests__/reducer.spec.js
src/reducer.js

Reducer's getValues now returns values. I assume this was a bug.
Normalization can now occur on formKeyed forms, if the action.key is defined.
Also, every version of eslint I tried gave me an error for redeclaration in on master.
I didn't add any tests for this, so please let me know if you want some, assuming that is was the right approach to take.

Normalization of keyed forms.

---

src/__tests__/reducer.spec.js
src/reducer.js

This works off #411 and passes the `fields` to `initializeState` as required by v4.
This makes the test from #411 pass now, which I **think** is all thats required to fix #377. I also tested this fix in an app that I just upgraded to v4 and it fixes the behavior I was seeing.

Fix initialising a nested array value with an object in v4

---

src/__tests__/setErrors.spec.js
src/setErrors.js

Previously was throwing error "TypeError: Cannot convert undefined or null to object"
This was being encountered in relation to async form submission [as seen in the submit-validation demo](http://erikras.github.io/redux-form/#/examples/submit-validation?_k=5igft0)
Credit: Implemented fix suggested by @box-turtle here https://github.com/erikras/redux-form/issues/446#issuecomment-166014354

Adds check for null state within setErrors

---

src/pages/faq/WebsocketSubmit.md

I noticed that the startSubmit and stopSubmit action creators are actually [ exported](https://github.com/erikras/redux-form/blob/master/src/index.js#L20) from the top level redux-form object. This just corrects the documentation.

Correct imported actions

---

src/wrapMapDispatchToProps.js

In my project, I create a wrapper around dispatch to catch promise rejections. Passing in that overridden dispatch function as follows would be nice:
```js
const WrappedForm = reduxForm(
{ form: 'login' },
state => ({}),
dispatch => ({ dispatch: bindSafeDispatch(dispatch) }),
)(LoginForm);
```
All tests pass =)

allow mapDispatchToProps to override dispatch property

---

src/__tests__/actions.spec.js
src/__tests__/reducer.spec.js
src/actionTypes.js
src/actions.js
src/createHigherOrderComponent.js
src/readField.js
src/reducer.js

I added a SWAP_ARRAY_VALUES action, reducer and tests.
Array fields can be modified by calling 
```javascript
swapFields(indexA, indexB)
```
This gets passed down as a prop just like addField() and removeField().
Hope you like it!

added swapFields() to deep forms

---

.editorconfig
.npmignore

IntelliJ defaults to 4 space indentation, but respects an editorconfig

Add editorconfig

---

src/examples/DeepForm.js
src/pages/examples/Deep.md

The title speaks for itself. You can now reorder the children by clicking up/down.

Added documentation & example for swapFields() to deep forms

---

package.json
src/createReduxFormConnector.js

IE8: 
You mentioned tests in #517, not sure what sort of tests you want? The existing tests all pass with this change, and the lib used for caching is an implementation detail not to be tested, right?
EDIT: If you meant test it as in functional test in the browser, the example from @gabrielpugliese-luizalabs runs with this change
My change to his example was just to show the validation

Update react-lazy-cache to not use getters

---

src/__tests__/updateField.spec.js
src/updateField.js

Fixes: https://github.com/erikras/redux-form/issues/559
This allows `initialValue` and `defaultValue` to be changed to falsey values, but prevents updates when there is no `initial` key on the field

Allow initial value to change to falsey value

---

src/__tests__/createReduxForm.spec.js
src/createHigherOrderComponent.js

This fix addresses an issue where forms with `asyncValidate` and `asyncBlurFields` specified call `asyncValidate` on every blur, even when the form has not been changed from its initial values.
@erikras please let me know if you have any other ideas on how to handle this one.

Disallow async validation when the form is pristine

---

src/pages/faq/ImmutableJs.md

The example for ImmutableJS currently has an [issue](https://github.com/itaylor/redux-form-immutablejs-example/issues/1) where a form with multiple fields will lose the content of other fields when you focus into a new field. This adds the second fix described in that issue, where all state is kept in an immutable object.

Update ImmutableJS example to fix focus issue

---

src/index.js

redux-form/native depends on react-redux/native which does not exist in react-redux 4+.
So the original redux-form has to be used instead. But it passes isNative as false, so most functions won't work.
A detection for react-native environment in index.js fixes the issue.

Fix for react-native 0.18+ with react-redux 4+

---

src/__tests__/handleSubmit.spec.js
src/createHigherOrderComponent.js
src/handleSubmit.js

fix for #580 
I hope there is no problem how it should be!
I'm not very sure if other Promise.reject in handleSubmit.js should return rejected promise with the validation errors. 
To be more specific,  here. https://github.com/haradakunihiko/redux-form/blob/master/src/handleSubmit.js#L30

Return promise when callback function is passed to handleSubmit

---

src/reducer.js

Potentially fixes https://github.com/erikras/redux-form/issues/393
I don't know where the code for the examples is, so I can't be sure if this is the source of the problem that was originally reported, but this fixes the problem that I was having, which is that fields which use a normalizer are unable to be reset with `resetForm`
The source of the issue here is that `_isFieldValue` is non enumerable, so the spread isn't copying it when computing the final object. However, `_isFieldValue` is needed for the reducer to handle the `RESET` action correctly.
There are a couple different approaches I can think of to handle this and this is probably the least clean, but in `fieldValues.makeField`, it's explicitly using `defineProperty`, which I can only assume is to make `_isFieldValue` non …

Preserve non-enumerable fields when normalizing

---

src/initializeState.js

I think calling initialize action with deep form does not pass new fields to my component.
`componentWillReceiveProps` function in ReduxForm component is trying to check the previous props and current props, but the previous form props and current form props is almost same when I define deeply nested form.(https://github.com/erikras/redux-form/blob/master/src/createHigherOrderComponent.js#L47)
The reason seems that the previous state is mutated in initialize reducer.
Sorry I could not write test cases to reproduce this, since I do not have much time for this right now...

Stop mutating state in initialize reducer 

---

src/__tests__/reducer.spec.js
src/normalizeFields.js
src/reducer.js

This is my first hacky stab at fixing #516 after I realized I needed this functionality yesterday :)
The code has some repetitiveness and isn't the cleanest at the moment. All current tests pass, and I added some minimal nested fields to existing tests to ensure they work. Regardless, we might want some more tests. I also made sure to replicate the work done in #562 recently to preserve non-enumerable keys, but we might want tests for that as well.
I took the approach of nested normalizers instead of using the nested key sytax (e.g. `foo[].bar`). I found it easier to walk down the state and normalizer objects at the same time with this approach. Using the nested key syntax was a little more difficult.
For an idea of the syntax here is a test I changed:
```js
it('should normalize simple …
```

Normalize nested fields

---

src/__tests__/createReduxForm.spec.js
src/readField.js

The field arrays were being mutated. They should be cloned whenever a field is added or removed.

cloned field array on change

---

src/__tests__/reducer.spec.js
src/normalizeFields.js

Here's code to handle the array syntax without nested properties (i.e. `'cats[]': (array) => ...`). This should pass the test introduced in dc581172784686af13754c0d07cb9f502eb9fde2. I also added a couple of other tests to ensure nested arrays work similarly.

Handle array normalization properly

---

src/__tests__/createReduxForm.spec.js
src/__tests__/reducer.spec.js
src/getValues.js
src/normalizeFields.js
src/readField.js

This PR fixes several bugs related to deep field mutations and normalization.
@jfairbank I apologize for [misunderstanding you before](https://github.com/erikras/redux-form/commit/dc581172784686af13754c0d07cb9f502eb9fde2#commitcomment-16075774) (I was on a layover between flights and not thinking straight). You were right. The array values need to be wrapped with `{value: }`.

Normalizing array fields

---

src/createReduxForm.js

The original writing will create a new function on every time ConnectedForm renders which leads shouldComponentUpdate not working.

Cache handleSubmitPassback function

---

src/__tests__/handleSubmit.spec.js
src/handleSubmit.js

The initial implementation of onSubmitFail was not reporting failures correctly for asynchronous validation functions, instead it didn't do anything. This was not the intended behavior.
This was an overlook on my part, as I didn't include this in the initial implementation. I hope I fixed up the issue before anyone else experienced this in their code.

[BUG] Fix support for async validation with onSubmitFail

---

src/__tests__/getValues.spec.js
src/getValues.js

Previously, form values were not being initialized from initialValues until the 2nd render cycle. This caused difficulties with server side rendering, double render cycles, and other related pains.
See https://github.com/erikras/redux-form/issues/621 for more discussion and links to possibly related issues.
This is addressed by falling back to `field.initialValue` when `field.value` is `undefined`
```js
/**
* Given a state[field], get the value.
*  Fallback to .initialValue when .value is undefined to prevent double render/initialize cycle.
*  See {@link https://github.com/erikras/redux-form/issues/621}.
*/
const itemToValue =
({value, initialValue}) => typeof value !== 'undefined' ? value : initialValue;
```
:memo: this also affected array fields. This was accounted for in both …

Fix #621 - Account for initialValues in getValues

---

docs/api/ReduxForm.md
src/__tests__/createReduxForm.spec.js
src/createHigherOrderComponent.js

Submitting this as a "straw man" solution to https://github.com/erikras/redux-form/issues/614. For my use case, I always want to perform asynchronous validation, even if the form is pristine (e.g. for required fields which have been touched) and this seemed like the most direct way to achieve it. Happy to discuss further if this is not ideal though!
--
This allows forms which use purely async validation to perform validation even if a field's value has been changed (e.g. show an error message if a user touches a required field, does not change it, then blurs it).
See https://github.com/erikras/redux-form/issues/614 and https://github.com/erikras/redux-form/issues/742 for example use cases.

Add alwaysAsyncValidate option, to always perform async validation on blur

---

README.md

This pull request fixes the invalid getting started link listed in the readme.
**Previous value**
* [Getting Started](http://redux-form.com/#/docs/GettingStarted.md)`
**Fix value**
* [Getting Started](http://redux-form.com/#/getting-started)

fix Getting Started link in README

---

package.json
src/__tests__/setup.js
src/setErrors.js

fixes #740
I was trying to reproduce it with tests without a success, but was easy to reproduce it in  
browser, I guess jsdom acts differently then browsers.
So i'm attaching screenshots of the issue before the fix and after:
Before failed validation:
After failed validation before the fix:
After failed validation with fix:
I also had to upgrade the jsdom because previous version has no File support.

fixes File transformed to Object after setErrors()

---

package.json
src/structure/immutable/__tests__/deepEqual.spec.js
src/structure/immutable/deepEqual.js

This PR addresses the issue shown in #919 where cyclic data structure would cause updates to fail, as `deepEqual` would keep comparing until reaching the maximum call stack size.
The solution is implemented by adding a dependency on `lodash.isEqualWith`, which offers support for cyclic structures.
This PR also preserves the requirements that the original deepEqual had, such as considering `''` and `undefined` equal, and comparing both Immutable and basic data structures in any nesting order.
This is specifically implemented through a customiser passed to `isEqualWith`, which, on encountering an `Immutable` data structure, performs the comparison manually through `Iterable`'s `every` method, and delegates back to `isEqualWith` again (this allows supporting plain objects inside Immutable …

Fix deepEqual on cyclic data structure

---

src/util/__tests__/every.spec.js
src/util/__tests__/toPath.spec.js
src/util/every.js
src/util/mapValues.js
src/util/toPath.js

This PR improves the performance of various utilities. These perf optimizations were previously done by `lodash`.
- Fix broken `every` tests (8590d4a6c32996326da942a39de4a450ff05bc80)
- Modify `toPath` to accept `null` literals (b1bbbe527966b78ab78b4d73d84b33e61c92250a)
- Remove closures created a runtime in `every` and `mapValues` and `toPath`

v6 — Improve perfs

---

docs/api/ActionCreators.md

A small update to the ActionCreator API docs. Adds the `field` parameter to the `startAsyncValidation` signature and describes the relevant behaviour.

add `field` parameter to docs for startAsyncValidation Action Creator

---

src/__tests__/getValuesFromState.spec.js

The following test shows that the behavior described in #383 is no longer reproducible using `v5.1.3`.

Add a test to invalid #383

---

.babelrc
.gitignore
babel-lodash-es.js
package.json

Lets package consumers tree-shake with webpack2, just like redux. In fact, I lifted the lodash-es babel plugin from the redux repo. 😉

Add es build

---

package.json
src/ConnectedFieldArray.js
src/Field.js
src/FieldArray.js
src/__tests__/Field.spec.js
src/__tests__/FieldArray.spec.js

Do you think it makes sense to use `shallowEqual` or even remove the entire `shouldComponentUpdate` as `Field` should be treated as a simple component to connects form's state and so `shouldComponentUpdate` shouldn't be part of the job.
Fixes #936

Use shallowEqual in shouldComponentUpdate

---

src/reduxForm.js

Hey, @gaearon, is a reasonable for a library to examine `module.hot`? This fixes #623.

Potential hot destroy fix

---

package.json

`classnames` is installed by isn't required.

v6 — Remove classnames dependency

---

package.json

Since Redux Form requires React, it is a good idea to add it to `peerDependencies`. Moreover it would indicate what React versions are compatible.

v6 — Add React to peer dependencies

---

webpack.config.base.js

The UMD builds must not include `redux` and `react-redux`.
```
> webpack src/index.js dist/redux-form.js --config webpack.config.development.js
Hash: 94a4e77b0d02a5717496
Version: webpack 1.13.0
Time: 2208ms
Asset    Size  Chunks             Chunk Names
redux-form.js  174 kB       0  [emitted]  main
+ 117 hidden modules
> webpack src/index.js dist/redux-form.min.js --config webpack.config.production.js
Hash: 72e7ef383112e424e4c2
Version: webpack 1.13.0
Time: 3278ms
Asset     Size  Chunks             Chunk Names
redux-form.min.js  57.9 kB       0  [emitted]  main
+ 117 hidden modules
```

v6 — Add Redux and React Redux as external dependencies to UMD builds

---

examples/immutable/package.json

`redux-immutablejs` requires `immutable` as `peerDependencies` but it wasn't added to the example's `dependencies` causing a `TypeError`.
See #962 for more details.

v6 — Add missing Immutable.js dependency

---

src/Field.js
src/FieldArray.js

Ignores `component` property when deciding to rerender `Field` and `FieldArray`, since, to allow stateless function components, must allow them to be different every time.

found focus-loss rerender bug. fixes #961

---

package.json
src/ConnectedField.js
src/ConnectedFieldArray.js
src/Field.js
src/FieldArray.js
src/reduxForm.js

Use Redux's memoization API to improve `ConnectedForm` performances by avoiding closure re-creations.
**NOTE:** It introduces 2 breaking changes:
- `react-redux` MUST match `>=4.3` (previously `>=4.0`)
- `form`, `touchOnBlur` and `touchOnChange` can't change over time. In order to prevent WTF behaviors, we could add a warning when `NODE_ENV` is not `production` if these props change.
**Disclaimer:** I haven't tested the examples since they rely on the latest published version on Redux Form instead of the local one.

v6 — Improve redux connector performances

---

docs/api/FormValueSelector.md

Object destructuring assignment had wrong variables names

v6 fix doc example of FormValueSelector

---

docs/api/Props.md

Found a typo while reading through the docs.

Fix typo in Props doc page

---

src/__tests__/createReduxForm.spec.js
src/readField.js

fixes #1090
The issue was that the prefix passed to `readField` wasn't being generated like it is for object fields. e.g. incorrect: `proposals[0].meta.items[].` correct: `proposals[].meta.items[].`
That is, `pathToHere` *may* actually contain indices for deeply nested stuff so you cannot use it.

fix(readField): Generate correct prefix when reading inside array fields, fixes #1090

---

src/__tests__/createReduxForm.spec.js
src/__tests__/fieldValue.spec.js
src/__tests__/getValuesFromState.spec.js
src/__tests__/initializeState.spec.js
src/__tests__/reducer.spec.js
src/__tests__/resetState.spec.js
src/__tests__/setErrors.spec.js
src/fieldValue.js

Fix of issue https://github.com/erikras/redux-form/issues/887 introduced another issue that didn't let you serialize state or use it with immutable.js. Whole background is presented below.
As far as I can see, everything started with this commit 87579e0, which was released with version 5.2.3.
In commit 7b5cb0f64911dffd2ac80e254719ec75333cb8f4 ([release 4.0.7](https://github.com/erikras/redux-form/releases/tag/v4.0.7)) two functions `makeFieldValue` and `isFieldValue` were introduced.
`makeFieldValue` is assigning not enumerable property to field object, so when trying to make Immutable from such object, not-enumerable property is lost.
It does matter, because on store, there is no `_isFieldValue` property assigned to field object, and because of that `isFieldValue` is failing when used in …

Make _isFieldValue property enumerable in store

---

examples/README.md
examples/react-widgets/.babelrc
examples/react-widgets/README.md
examples/react-widgets/devServer.js
examples/react-widgets/index.html
examples/react-widgets/package.json
examples/react-widgets/src/ReactWidgets.md
examples/react-widgets/src/ReactWidgetsForm.js
examples/react-widgets/src/index.js
examples/react-widgets/src/userData.js
examples/react-widgets/webpack.config.dev.js
examples/react-widgets/webpack.config.prod.js

Hi @erikras 
I have added an example which will demonstrate how to use `redux-form` with `react-widgets` components. 
Mostly it works out of the box but we need to trick `onChange` and `onBlur` event as and when required.
* `react-widgets` is heavily dependent on their css so there isn't exact UI in our example. I have tweaked root css from `index.html`.
* Their [MultiSelect](http://jquense.github.io/react-widgets/docs/#/multiselect?_k=os7mqb) component has a warning error for the `value` props as it expect `array` and we are passing string , though it works as expected.
* I haven't covered `DateTime` and `Number` Components (Please let me know if you would like to add) 
* I have also implemented how to initialize the form so that users have better understanding how to do that with …

Adding react-widgets example

---

src/ConnectedField.js
src/ConnectedFieldArray.js
src/createFieldProps.js
src/reduxForm.js

We can substitute these helpers by `Function#bind` and closures.
Removing them ease the configuration of `LodashModuleReplacementPlugin` because it no longer requires `placeholders` to be enabled.

v6 — Remove lodash's `partial` and `partialRight`

---

src/ConnectedField.js
src/Field.js
src/__tests__/Field.spec.js
src/__tests__/createFieldProps.spec.js
src/createFieldProps.js

Fixes #1024.
Moved `getSyncError()` from `ConnectedField` to `Field`.

Fixed bug where field was not rerendering when sync error changed

---

src/__tests__/formValueSelector.spec.js

This test is broken. `'rodent.mice'` returns a `List` instead of an `Array`.
See #1106 
```diff
1) formValueSelector.immutable should get a deep array:
Error: Expected { rodent: { mice: List [ "Jaq", "Gus", "Major", "Bruno" ], rat: { hog: 'Willbur' } } } to equal { rodent: { mice: [ 'Jaq', 'Gus', 'Major', 'Bruno' ], rat: { hog: 'Willbur' } } }
+ expected - actual
{
"rodent": {
-    "mice": {
-      "__altered": false
-      "__hash": [undefined]
-      "__ownerID": [undefined]
-      "_capacity": 4
-      "_level": 5
-      "_origin": 0
-      "_root": [null]
-      "_tail": {
-        "array": [
-          "Jaq"
-          "Gus"
-          "Major"
-          "Bruno"
-        ]
-        "ownerID": [undefined]
-      }
-      "size": 4
-    }
+    "mice": [
+      "Jaq"
+      "Gus"
+ …
```

v6 — Add broken formValueSelector test case

---

src/events/__tests__/getValue.spec.js
src/events/getValue.js

#1100 added automatic number parsing of `<input type="number">` fields but if the field is empty it currently applies `parseFloat` to an empty string, which produces `NaN` which could be argued either way as right or wrong, but this has the consequence of making the `<input>` warn in Google Chrome with:
> The specified value "NaN" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
This happens on every re-render, once that field has been touched. Using `undefined` also invokes the warning, the only thing that doesn't is the default empty string or a string that is a valid number.
Because of #1089 I can't create a JSBin to reproduce, but here's some code:
```js
console.clear();
const { createStore, combineReducers } = …
```

fix(type=number): Don't parseFloat empty value strings, they NaN

---

src/__tests__/readFields.spec.js
src/readField.js

I am using a key-value map as `intialValues`. The map is coming from server but the server has no knowledge about values so it sends all values as string. 
String `"true"` is a valid value for the `checked` attribute in react so it should also be for redux-form.

'checked' attribute should be set when string boolean like "true" is used

---

docs/api/ActionCreators.md

As mentioned in #1140 
> third parameter `fields` doesn't seem to apply to v6 since redux-form no longer needs to define the form fields in the form config.

[Docs] Remove not relevant to v6 params and description from 'initialize' action creator description

---

src/__tests__/readFields.spec.js
src/isChecked.js
src/readField.js
src/updateField.js

Reworked how 'checked' is determined to allow string values. Originally started in #1184.
It's a shame that `Boolean('false') === true`. Silly javascript!
This change makes any case of `'true'` or `'false'` convert properly to boolean for checkboxes.
@ooflorent Review?

Fixed problems caused by #1184

---

src/ConnectedFieldArray.js
src/__tests__/FieldArray.spec.js

Added missing move() and removeAll() methods to FieldArray prop

---

docs/api/ReduxForm.md
src/__tests__/handleSubmit.spec.js
src/__tests__/reduxForm.spec.js
src/handleSubmit.js
src/reduxForm.js

Addresses #1201.
Also removed `returnRejectedSubmitPromise`. That was put in as a stopgap measure to avoid a breaking change, but I think the promise that is returned from submitting should always be rejected if there was an error.
@ooflorent, please review.

Always return rejected promise when submit is rejected

---

package.json

Allows tests to run on windows platforms.
Switched script "test:watch" to append options to the "test" script target.

Change single quotes in test scripts to escaped double quotes

---

docs/api/ReduxForm.md
src/__tests__/reduxForm.spec.js
src/reduxForm.js

Rarely (?) used functionality from `v5`.
Also specifically whitelisted the props that `redux-form` provides to the wrapped component.

Added propNamespace functionality

---

docs/api/ReduxForm.md
examples/README.md
examples/asyncValidation/src/AsyncValidation.md
examples/simple/src/Simple.md
examples/submitValidation/src/SubmitValidation.md

Came across a few things when reading docs. This pull request fixes:
1. Broken links between validation examples, e.g. try to click the "Submit Validation" link in this example on [Github](https://github.com/erikras/redux-form/blob/v6/examples/asyncValidation/src/AsyncValidation.md) and [redux-form.com](http://redux-form.com/6.0.0-alpha.15/examples/asyncValidation/).
2. A couple of typos
Also noticed two more potential changes in the [`reduxForm()`](http://redux-form.com/6.0.0-alpha.15/docs/api/ReduxForm.md/) docs, which I could add to the PR:
* **Blue**: This link seems superfluous and the placement would suggest it relates to all options or options in general, which is not the case.
* **Red**: As mentioned in #726, section 12, the ambition is to have docs navigable on both Github and …

[v6] Fix broken links and typos in docs

---

src/events/__tests__/createOnDrop.spec.js
src/events/createOnDragStart.js
src/events/createOnDrop.js

Bumped into https://github.com/erikras/redux-form/issues/1088 and the solution to stop these errors (and to unbreak drag and drop on IE) is to just change the dataKey to 'text. 
The [stack overflow question](http://stackoverflow.com/questions/26213011/html5-dragdrop-issue-in-internet-explorer-datatransfer-property-access-not-pos) mentioned in the referenced issue suggests this as well FWIW.

Fix drag and drop on IE

---

examples/immutable/src/index.js

I am not able to understand the immutable example, so I decided to run it locally... just to find out that it was not using the `reducer.js` file
So I decided to amend the example, but I receive a JS error in console:
```
_immutable.reducer.validation is not a function
```
I thought it might be a good idea to PR my changes to have something to fix.
Eventually I am interested in an example with immutable and initialValues to use in a react-native app.
Note: To run the example locally a user must `npm install` the root of the project not just the individual example.

[v6] DOC broken immutable example

---

src/__tests__/createReduxForm.spec.js
src/initializeState.js

Don't overwrite user input on fields not present in initialValues when  `overwriteOnInitialValuesChange: false`

---

docs/GettingStarted.md
docs/MigrationGuide.md
docs/faq/EnterToSubmit.md

Assistive technologies makes good use of `for` in order
to help people who depend on screenreaders.
I believe in making the web an inclusive place and I think libraries like this promoting best practices is a good place to start. Including the `for` attribute in the examples increases the chance that developers who copy and paste from the docs will include it in their own markup.
Your PR, should you choose to accept it, will add the `htmlFor` attribute to `<label>` elements in the examples, increasing the chance that other developers will include it in their codebase.

Use the `for` attribute for label elements

---

package.json
src/ConnectedFieldArray.js
src/Field.js
src/FieldArray.js
src/util/shallowCompare.js

This replaces the `react-addons-shallow-compare` dependency with a small local implementation of the same behavior, to avoid introducing a peer dependency on a specific minor version of React 15. See #1319 for the original discussion around this. Copying the description here for ease of viewing:
> Currently there is a dependency on `"react-addons-shallow-compare": "^15.2.0"` in the [package.json for rc.3](https://github.com/erikras/redux-form/blob/v6.0.0-rc.3/package.json#L50). This causes a problem for those of us still using React 15.1 or lower with NPM 2, since that package has a peer dependency on React 15.2.
> 
> Since the functionality provided by that package is super minimal, might it be possible to replace it with a simple local implementation to prevent weird dependency issues …

[v6] Replace react-addons-shallow-compare with local implementation

---

README.md

Looks like this got missed in the initial rc.4 release?

Add link to rc.4 docs

---

src/ConnectedField.js
src/__tests__/Field.spec.js

Here's a simple fix. I noticed that if a field has a non-empty initial value, then I clear the field and reinitialize the form with an empty string, the field should become pristine, but does not (as of 6.0.0-rc.4). This happens because the code treats an empty string as no value at all and falls back to the original initial value. This pull request fixes the problem by expecting 'undefined' to be the only value that indicates the initial value is missing. Test included.

[v6] Fixed the pristine/dirty state of fields that get reinitialized to an empty value.

---

src/__tests__/FieldArray.spec.js
src/reducer.js
src/structure/immutable/__tests__/splice.spec.js
src/structure/immutable/index.js
src/structure/immutable/splice.js
src/structure/plain/__tests__/splice.spec.js
src/structure/plain/splice.js

Splice methods didn't use to add the value you passed them into the
value array. Fixed this logical issue for both plain and immutable
structures.
Fixes #1490.

Fixed splice methods and added tests for ImmutableJS splice.

---

examples/README.md

I tried to follow the [general example instructions](http://redux-form.com/6.0.0-rc.1/examples/) to get them running on my local machine, but I ran into missing dependencies like Mocha, babel-register etc. 
I noticed that this wasn't an issue when I first did a `npm install` of the main project.

Example docs, run main npm install first

---

src/__tests__/reducer.unregisterField.spec.js
src/reducer.js
src/structure/immutable/expectations.js

`findIndex()` returns -1 for non existing values. When feeding -1 to
the `splice()` method, the first value of the `registeredFields` array
is erroneously removed.
Fixes #1460.

UNREGISTER_FIELD should not remove fields that don't exist

---

docs/api/ReduxForm.md
src/reduxForm.js

This addresses some pain points as outlined in #980 #817 #1511 and allows you to call different apis for different blurred fields.

expose blurredField in asyncValidate

---

src/__tests__/hasError.spec.js
src/hasError.js
src/reduxForm.js

Fields can have object values, in which case we need a way to set an
error at the object level. The library will pass "_error" to the Field as
the "error" prop to be displayed, but isValid wasn't respecting it as an error.
Also reused `isValid` selector in the `reduxForm` `connect` function so that we're not duplicating logic.
Fixes #1107

Allow Fields to have an "_error" assigned to them

---

src/ConnectedField.js
src/ConnectedFieldArray.js

This will force the component to re-render when submitting so that we
can disabled / enable components based on submit state.
Fixes #1122

Pass "submitting" as prop to ConnectedField and ConnectedFieldArray

---

src/__tests__/reduxForm.spec.js
src/reduxForm.js

Adds `pure` option.
Needed if a parent component re-renders and a child component fetches state from context / any other source that isn't checked in the `shouldComponentUpdate`.

pure option

---

docs/MigrationGuide.md

- Add known issue with react-hot-loader v1 to migration guide
closes #1129
Apologies on the whitespace changes.  If you view the rich diff, you will see the markdown rendering is unaffected.  I can remove if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/erikras/redux-form/1566)

Add react-hot-loader issue to docs (fixes #1129)

---

src/ConnectedField.js
src/ConnectedFields.js
src/__tests__/Fields.spec.js
src/__tests__/createFieldProps.spec.js
src/createFieldProps.js

The custom props weren't going into the right place in the props passed to `component`. Fixes #1583.

Put custom props in proper place in Fields

---

src/ConnectedFieldArray.js
src/__tests__/FieldArray.spec.js

`FieldArray` was rerendering on every single value change. It doesn't anymore. Fixes #1578.

Fixed FieldArray rerender bug

---

src/__tests__/FieldArray.spec.js
src/__tests__/actions.spec.js
src/__tests__/reducer.arrayPush.spec.js
src/reducer.js
src/structure/immutable/__tests__/splice.spec.js
src/structure/immutable/expectations.js
src/structure/immutable/index.js
src/structure/immutable/splice.js
src/structure/plain/__tests__/splice.spec.js
src/structure/plain/expectations.js
src/structure/plain/index.js
src/structure/plain/splice.js

Allowed pushing, unshifting, and inserting of `undefined` into a field array. Previously, after a `push()`, the value passed to your input would be `{}` instead of `''`.
Made arrays be `Immutable.List` when using `redux-form/immutable`. Fixes #1574.

Fixed immutable array reducer bug

---

docs/api/Reducer.md

Remove old details from V6 documentation about the normalizer function which no longer exists in reducer.js
The details also included a broken link to the old ReducerNormalize.md which no longer exists as well. Since this information is deprecated now and there is a new way to normalize form values ([normalizing functions](http://redux-form.com/6.0.1/examples/normalizing/)), it's worth removing from the docs now.

Remove deprecated reducer.normalize details from Reducer.md in documentation

---

docs/ValueLifecycle.md
docs/api/Props.md

- The [Value Lifecycle](http://redux-form.com/6.0.1/docs/ValueLifecycle.md/) page has a broken image due to its src url pointing to a nonexistant image. It has been corrected to point to `https://github.com/erikras/redux-form/blob/master/docs/valueLifecycle.png`
- The [Props](http://redux-form.com/6.0.1/docs/api/Props.md/) page has two broken links, one to the reduxForm() api docs & the other to `/propTypes.js`. Those two links have been corrected as well.

Fix broken links & image in documentation

---

docs/api/Field.md

Currently in the documentation in Field.md, it says that 
> ## Props
>These are props that Field will pass to your wrapped component. **All the props provided to your component by redux-form are divided into input and meta objects.**
Unfortunately, for a newcomer to V6, this might be confusing since there is no explanation of where custom props come into play - only that there are props are divided into input & meta objects. 
(Also the use of the phrasing _`All the props provided to your component...are divided into input and meta objects`_ makes it sound like there is no other props available to Field besides input & meta).
**Change Proposed:**
I'd like to propose to add a sentence after the input & meta objects explanation, to explain that custom props are merged into the props that …

Add explanation on how custom props are given in Field & clarify props given by Field

---

docs/api/ActionCreators.md
docs/api/Field.md
docs/api/FieldArray.md
docs/api/Fields.md
docs/api/FormValueSelector.md
docs/api/Props.md
docs/api/README.md
docs/api/Reducer.md
docs/api/ReducerPlugin.md
docs/api/ReduxForm.md
docs/api/Selectors.md
docs/api/SubmissionError.md

Addresses #1214 
Changes proposed:
- Add source code links on the api/README.md for each section block.
- Add source code links on each api documentation page to its respective github source. For `props` & `reducer.plugin`, I referred to their inline references in reduxForm.js & reducer.js
- Add Selectors section block to bottom of api/README.md to reflect the new Selectors.md documentation

Add Source code links to API documentation & Add selectors section to api/README.md

---

examples/initializeFromState/src/InitializeFromState.md

This issue is mentioned in https://github.com/erikras/redux-form/issues/1648.
Currently, the example documentation refers to the method of dispatching `INITIALIZE` as if it is the only method to reinitialize the form with new pristine values. `enableReinitialize` & `keepDirtyOnReinitialize` are missing from this section.
This change adds documentation about `enableReinitialize` & `keepDirtyOnReinitialize` to the Initialize From State example as another option.

Add missing documentation on `enableReinitialize` in InitializeFromState example docs

---

.babelrc
package.json

Currently the jsnext:main build of redux-form contains CommonJS code instead of ES module code.  
Removing the `transform-es2015-modules-commonjs` babel plugin fixes the issue and outputs the correct format.

Fix build:es output by replacing babel-preset es2015 with es2015-no-commonjs

---

src/structure/plain/__tests__/getIn.spec.js
src/structure/plain/getIn.js

`getIn` seems to be the highest low hanging fruit when it comes to performance
Optimized for the most common use-case: path length of 1, 2 or 3 items
On my chrome it shows ~5x improvement
jsPerf is down, so here's a benchmarkJS fiddle:
https://jsfiddle.net/9vqm86eu/1/

Improved performance of getIn()

---

src/__tests__/isPristine.spec.js
src/isPristine.js

I have a situation where a number field gets set to `0` with an initial value of `null` and the form and field don't get marked as dirty.
Note that because it's a number field `0` in this case is of type `number` not `string` which `isPristine` doesn't seem to accommodate for.
In the case of `'0'` (ie.. string) `isPristine` behaves as expected already.
If this is the desired behaviour are there any suggestions for a work around?

isPristine does not differentiate between null and 0

---

src/__tests__/createReduxForm.spec.js
src/createHigherOrderComponent.js
src/createInitialState.js
src/readField.js
src/reducer.js

This should fix the long living bug #621.
First round
===========
My first try was #1025, I tried pass a default field state to [updateField](https://github.com/erikras/redux-form/blob/v5.3.1/src/updateField.js#L8) so that updateField can read initial value from given state.
But I forgot the the validate function which causes validate function cann't read initial values at first render.
Second round
============
My second try was #1061, I tried pass initial values to validate function. But I forgot a form may have no initial values or only have partial initial values which causes #1241.
Third round
=====================
I thought I can create a initial form state before creating fields, so that updateField and validate function can both read initial values.

Create a initial form state before creating fields

---

docs/api/ReduxForm.md
src/__tests__/actions.spec.js
src/__tests__/handleSubmit.spec.js
src/__tests__/reducer.change.spec.js
src/__tests__/reducer.stopSubmit.spec.js
src/actions.js
src/handleSubmit.js
src/reducer.js
src/reduxForm.js

See #1708
The change to the `if (valid)` check in handleSubmit.js is still a bit of an hack. I think the cleanest solution would be to call `validate` there, similar to `asyncValidate`.

Option to keep submit errors on change

---

src/structure/immutable/__tests__/deepEqual.spec.js
src/structure/immutable/deepEqual.js
src/structure/plain/__tests__/deepEqual.spec.js
src/structure/plain/deepEqual.js

`dirty(undefined, false)` should be `false`. It was `true`.
Intuitively, clicking twice on a check-box should return it to
pristine, which is false atm (unless the checkbox is initialized with
`false`).
Same behavior as `empty` and `undefined` for a string.
Also decreases code complexity. If both `value` and `initial` are falsey,
return “equal true”.
Comes with tests, both `immutable` and `plain` structures are covered.
I would be very pleased to see it shipped. :hatching_chick:

Improve dirty handling for checkboxes

---

src/ConnectedField.js
src/ConnectedFieldArray.js
src/ConnectedFields.js
src/Field.js
src/FieldArray.js
src/Fields.js

Redux `connect()` returns a new class. Currently, each `ConnectedField`, `ConnectedFields` and `ConnectedFieldArray` is connected to redux, thus creating many classes. This change connects `ConnectedField`, `ConnectedFields` and `ConnectedFieldArray` only once.
In a field array, if we would like to preserve state of our component, we need to use a key that identifies the element, instead of array index. However, doing so, `Field`, `Fields` and `FieldArray` detects that it is now bound to a new field name and discards the old connected class and `connect` again. React sees that the class is different, thus discards the old virtual DOM, along with the `component` and its state.
By using `mapStateToProps(state, ownProps)` and `mapDispatchToProps(dispatch, ownProps)`, we can [dynamically map …

Reuse connected ConnectedField, ConnectedFields and ConnectedFieldArray

---

src/structure/immutable/__tests__/setIn.spec.js
src/structure/immutable/index.js
src/structure/immutable/setIn.js

ImmutableJS's `setIn` (and thereby `updateIn` / `deleteIn` / etc...) do not seem architected to work with a mixture of `Map` and `List` objects. The call assumes that an "unset" value can only be one thing, and only has one resolution path for when that value is empty. (Namely, add it as an empty map) [See Immutable-js Source](https://github.com/facebook/immutable-js/blob/master/src/Map.js#L802)
This leads to the issue found in #1574 where we get the infamous error:
Uncaught TypeError: list.splice is not a function
When using immutable-js with `FieldArray`. The focus / blur events are calling `setIn` on `fields.fieldName[0].touched` etc... which causes the `fieldName` part of the tree to be instantiated as `Map` instead of a `List`.
Actual | Expected
------------ | -------------
```{ …
```

Support for ImmutableJS setIn array paths

---

examples/fieldArrays/src/FieldArraysForm.js
src/ConnectedFieldArray.js
src/__tests__/FieldArray.spec.js
src/createFieldArrayProps.js

With this PR, if you view the `fieldArrays` example and submit before doing anything, it will display the error for not adding any members.
I can't fix the CSS for this because even when running a local example it links out to http://redux-form.com/6.0.2/bundle.css. 
In fixing this it exposed another bug. If you add any members, then you remove all members you can't get the `.touched` property, so the error never shows up again. Once you add a member `form.fieldArrays.fields.members` is converted from an object to an array. Later when the `TOUCH` action happens it can't add the `.touched` property because it's still an array even after the last member is gone. I spent about an hour tracking this down and trying to figure out how to fix it, but I don't know if I can fix it without …

Add meta.touched to FieldArrays

---

src/reduxForm.js

fixes #1704
removes reject from `listenToSubmit` cause no one handles this reject

fixes #1704 `Uncaught (in promise)`

---

src/__tests__/createFieldProps.spec.js
src/createFieldProps.js

Ref: https://github.com/erikras/redux-form/issues/1634
This allow creating own meta properties for fields via the reducer:
```js
combineReducers({
form: form.plugin((state, action) => {
if (action.type !== 'redux-form/CHANGE') return state;
return setIn(state, 'fields.' + action.meta.field + '.myCustomProp', true);
})
});
```
results are passed to the `meta` object:
```jsx
<Field name='foo' component={renderFancy} />
const renderFancy = ({input, meta: {myCustomProp}}) => 
<input type="text" {...input} style={myCustomProp ? {color: 'red'} : null} />
```

Implemented custom meta props. Fixes #1634

---

docs/DocumentationVersions.md

Description:
-----
There is a duplicate link for [5.2.3](http://redux-form.com/5.2.3/) in `DocumentationVersions.md`, which displays in the live documentation as:
>- [5.2.3](http://redux-form.com/5.2.3/)
>- [5.2.3](http://redux-form.com/5.2.3/)
Second,`DocumentationVersions.md` is missing links to 6.0.1, 6.0.2, 6.0.4 patch versions. Not sure if this was intentional, but it might be nice to put those here for archival reasons since they're in gh-pages anyway, up to you. Let me know what you think about this.
Lastly, there's a big line break jump between version 6 documentations & the version below it, which cause some fragmented formatting starting at v6.0.0-alpha-4 (https://github.com/kevinzwh/redux-form/blob/master/docs/DocumentationVersions.md)
Changes proposed:
-----
- Removed …

Remove duplicate 5.2.3 docs link and upkeep of v6 patch docs links

---

src/__tests__/reducer.plugin.spec.js
src/reducer.js

This argument is the state before the redux form and other plugins reduce the action to the state provided as the first argument.
This fixes issue #1817

Adds a third argument when calling reducer plugins

---

src/ConnectedField.js

Regression caused by src/ConnectedField.js changes in PR #1589, partly breaking feature added for #927 
`custom` is now initialized before props.ref is assigned. This means that the ref prop will not reach a text-based component like `input`.
The fix is trivial, just need to assign ref as a property to `custom` instead of to `props`.
Being in `custom`, it will end up in both text and React components.
Testing the change locally seems to indicate that getRenderedComponent() works properly again.

Fix ConnectedField withRef/getRenderedComponent() regression for text components

---

src/components/Nav.scss

I use MacOs with changed settings of scrollbar behaviour, they always shown. And with this setup brand name is wrapped into two lines. This small styles change fixes it.
Before:
After:

Prevent wrapping brand name

---

src/ConnectedFieldArray.js

In commit 89e183f, additional properties were extracted from `this.props`, which in turn removed them from the `...rest` variable.
This commit manually adds the `name` prop back into the generated lists of props.
I'm not 100% sure that this fixes all of the things that were changed in that commit, but it does fix the `FieldArray` `component` not getting this property.

Fix `name` prop not being passed down to children

---

examples/immutable/src/index.js
examples/immutable/src/reducer.js

Description
----
The `immutable` example lacks an example of the necessary import of:
```
import { reducer as form } from 'redux-form/immutable' // <--- immutable import
```
Changes proposed:
----
- Extract reducer import statements in `immutable` example `index.js` file into its own file `reducer.js`
- Add `reducer.js` raw code in the `immutable` example in docs.'
----
Fixes #1662

Fix #1662: Add reducer import code to Immutable example in docs

---

docs/api/Field.md
docs/api/Fields.md
src/__tests__/Field.spec.js
src/__tests__/Fields.spec.js
src/createFieldProps.js

Description
----
Currently, `parse` and `format` props are called with only the field `value`.:
>`format : (value) => formattedValue` [optional]
>`parse : (value) => parsedValue` [optional]
As described in #1677, there are cases where it would be beneficial for it to be called with the field `name` such that the interface for both would become:
>`format : (value, name) => formattedValue` [optional]
>`parse : (value, name) => parsedValue` [optional]
It would allow for fields of the same component that rely on different types of values to be differentiated by `name` in the value lifecycle through `parse` & `format`.
Changes Proposed
----
- Add field `name` as a second input to `parse` & `format`
- Update tests for `parse` & `format` for both Field & Fields components with new `name` …

Fix #1677: Add `name` argument to `parse` & `format` props for Field + Fields

---

src/__tests__/handleSubmit.spec.js
src/asyncValidation.js
src/reduxForm.js

We're at the end of the promise chain already. There's already a rejection coming from above (either by `throw` or `reject`).
Hope this helps.
Fixes #1297.
PS: Thanks for all the awesome @erikras and all others involved.

fix asynch validation uncaught promise

---

src/__tests__/reducer.arrayPush.spec.js
src/structure/immutable/splice.js
src/structure/plain/splice.js

The constructs being used in argument assignment only account for undefined values, for example the array property below:
```
const splice = (array = [], index, removeNum, value) => {
```
If the array value is null, it will not be assigned to be an empty array. This causes any code that assumes array will be an actual array (and not null) to break.
I've added a test to demonstrate the bug, and a simple fix. Basically, do the assignment outside of the arguments, so that null values are handled properly, and list.count() and array.length don't fail.
This might affect other areas of the codebase. If the foo = bar arg assignment construct is being used anywhere, the code in that function has to be protected against null values (or don't use that arg construct, just do default arg assignment …

arrayPush should handle a null leaf value

---

package.json

v5 is centered around the `connect()` rewrite described in this PR: https://github.com/reactjs/react-redux/pull/416
The changes expands the API and rewrites all of the internals but preserves existing functionality, so it’s really non-breaking ([reference](https://github.com/reactjs/react-redux/pull/416#issuecomment-239678590)). It also solves bugs related to nested connected components’ subscriptions getting triggered our of order for our app (which was actually the original motivation for the PR, see https://github.com/reactjs/react-redux/pull/416#issuecomment-250885794 and https://github.com/reactjs/react-redux/pull/416#issuecomment-250892326), so we’re switching over.

Update react-redux dependency range to include v5 prereleases

---

examples/material-ui/src/MaterialUiForm.js

I spent a while trying to figure out why my `disabled` prop wasn't being passed to the SelectField, where it was working elsewhere.
I'd copied the function from here, and just figured out the issue that we were losing any other props passed in to the component.

Add custom props to material-ui select field

---

src/events/__tests__/getValue.spec.js
src/events/getValue.js

Removes the `parseFloat` for number and range types so that decimals can be entered. Fixes #1383.

Store number input value as string to fix #1383

---

docs/api/Selectors.md
src/createAll.js
src/selectors/__tests__/getFormSyncErrors.spec.js
src/selectors/getFormSyncErrors.js

I found myself needing to display all errors in a single location, as an unordered list, outside of the fields components. This adds a simple selector to return synchronous validation errors.
Also refers to https://github.com/erikras/redux-form/issues/1923

Created a selector for synchronous errors

---

src/reducer.js

Form level `syncError`doesn't need to be removed during a field `CHANGE` action, and is properly removed during `UPDATE_SYNC_ERRORS`. This fix will correct the following issue:
- Form has form level error, triggered by the validate function returning `{_error: "missing required fields"}`
- The next CHANGE event clears `syncError: true` from the form state, making the form as `valid` when the form level `error: "missing required fields"` still exists in the state.
This was added by @ortex in v6.1.1 (issue #1925, PR #1945)
Hey @ortex, can you double check my logic above? I just want to make sure I'm not undoing something you were trying to fix that I haven't noticed.
Thanks!

remove the deletion of form level syncError during field CHANGE action.

---

src/index.js

One-line fix to enable getFormSyncSelector. Needed it to make a feature

added missing export for getFormSyncErrors

---

docs/api/ReduxForm.md
src/__tests__/defaultShouldValidate.spec.js
src/__tests__/reduxForm.spec.js
src/defaultShouldValidate.js
src/reduxForm.js

Creates a new config property for `reduxForm` called `shouldValidate` which allows developers to have full control over when sync validation happens.
Provides a solution for #1965.

Create shouldValidate config property

---

src/__tests__/reduxForm.spec.js
src/reduxForm.js

Andd the store's version of the initialValues is updated. The values also get set to this new initialValue if keepDirtyOnReinitialize is false.
closes #1902
@skolmer

ReduxForm resets it's initialValues if enableReinitialize is true

---

src/reducer.js

I found that when using Immutable in my Redux store, and using the `enableReinitialize` and `keepDirtyOnReinitialize` options everything would work fine until I changed one of the values in my form, and then changed the `initialValues`. All other fields then wouldn't update their value to the new initial value. They were getting considered as `dirty`.
`name` in the reducer was evaluating to `undefined`, so when used with `getIn()` below, it was getting the entire form `values` + `initialValues` as the values for the specific field. Then the equality check on the entire values map shows that one of the fields changed, so it considers the field dirty. But of course as it's the entire values map it will always consider every field in the form dirty even if only one is.
Wasn't sure how to add …

Fix re-initializing when using Immutable

---

src/__tests__/handleSubmit.spec.js
src/handleSubmit.js

If an error is thrown by the onSubmit function that is not a SubmissionError, it will now be re-thrown instead of silently ignored. It will retain the previous behavior if you pass an onSubmitFailed prop - personally I don't like that too much, but it would be a breaking change according to the test suite.
Should fix #1859.
Would appreciate feedback!

Don't swallow errors in `onSubmit`

---

docs/api/ReduxForm.md

Documented the three arguments passed to `onSubmit`. The third `props` argument [was added recently](https://github.com/erikras/redux-form/releases/tag/v6.0.2), but still not documented. I found it useful to know!

Document arguments passed to onSubmit function

---

package.json

Add "module" entry to package.json in order to support ES modules with the latest Webpack.
See: https://github.com/webpack/webpack/issues/1979#issuecomment-234873209

Add "module" entry to package.json

---

src/reduxForm.js

This relates to #1990  and #2016. This patch suppresses unregister() for a field if the containing form is still mounted elsewhere, and the containing form itself is being unmounted, rather than just the field itself.
This is useful in conjunction with destroyOnUnmount: false when you have small, self-contained sub-forms embedded in larger forms, or different parts of the UI.

Don't unregister fields on unmount when a single form is concurrently mounted

---

examples/react-widgets/package.json
examples/react-widgets/src/ReactWidgets.md
examples/react-widgets/src/ReactWidgetsForm.js

The react-widgets example was erroring when using `{...rest}` like this:
```
const renderMultiselect = ({ input, ...rest }) =>
<Multiselect {...input}
onBlur={() => input.onBlur()}
value={input.value || []} // requires value to be an array
{...rest}/>
```
With this error:
> warning.js:36 Warning: Unknown prop `meta` on <div> tag. Remove this prop from the element. For details
I removed rest and used explicit parameters.
I am not convinced this is the best way, the other way would be to do something like this:
```
const colors = [ { color: 'Red', value: 'ff0000' },
{ color: 'Green', value: '00ff00' },
{ color: 'Blue', value: '0000ff' } ]
/* eslint-disable no-unused-vars */
const renderDropdownList = ({ input, meta, ...rest }) =>
<DropdownList {...input} {...rest} />
const renderMultiselect …
```

remove errors caused by using {...rest} and add DateTimePicker example

---

src/__tests__/readField.spec.js
src/readField.js

Yet another instance of issue #375.
Specifically, any array that contained non-immediate descendants (e.g.
arrayField[].deepObjectField, or arrayField[][], but not plain old
arrayField[]) would remain the same instance if any of its descendant
fields were updated but no items were added to or removed from the
top-level array.
The issue was that we were only making a fresh copy of the array (that's
`changed = true`) in the case where it a raw-value array item was
changed, but not in the general case.

Fix arrays of object fields (v5)

---

src/ConnectedFields.js
src/__tests__/FormSection.spec.js

This fixes #2148,
Currently a `Fields` component within a `FormSection` needs to know what the FormSection prefix is in order to access the fields inside the `Fields` component. This PR makes it so that the form sectionPrefix doesn't carry over into the `Fields` component props. Also included is a test case.
```javascript
<FormSection name='parent'>
<Fields name={['foo', 'bar']} component={renderFields} />
</FormSection>
...
// current
const renderFields = ({parent: {foo, bar}}) => (
<div>
<input {...foo} />
<input {...bar} /> 
</div>
)
// proposed
const renderFields = ({foo, bar}) => (
<div>
<input {...foo} />
<input {...bar} /> 
</div>
)
```

a Fields component within FormSection should not need to know the FormSection name

---

src/structure/plain/setIn.js

See https://jsperf.com/plainsetin for benchmark. Makes a huge difference in real world due to much less stress on GC.

Rewrite setInPath for 2.5x speed improvement.

---

docs/api/FieldArray.md
src/__tests__/FieldArray.spec.js
src/__tests__/createFieldArrayProps.spec.js
src/createFieldArrayProps.js

It's probably not well know but creating functions inline within a render call is a performance hit since new functions are created on each re-render. This in turns clutters our memory space and makes the GC work unnecessarily.
To avoid this it would be helpful if `fields.map`, `fields.forEach`, and `fields.reduce` passed along a `fields` reference to the callback provided. This allows us to create a callback method that can be passed directly the `fields.map` while still allowing access to `swap`, `remove`, `pop`, etc.
Example:
```javascript
const renderSubFields = (member, index, fields) => (
<li key={index}>
<button
type="button"
title="Remove Member"
onClick={() => fields.remove(index)}/>
<h4>Member #{index + 1}</h4>
<Field
name={`${member}.firstName`}
type="text" …
```

[FieldArray] Pass reference to the `fields` prop in map, forEach, and reduce callbacks

---

src/structure/plain/__tests__/deepEqual.spec.js
src/structure/plain/deepEqual.js

Hello,
Long story short, in our project we have a NumberField that gets number values (int and float) from the user and keeps them as a valid js number in the store. However, if they want to enter floating points, as soon as they start typing `"."` we can't transfer that to a number (as `Number("10.") === 10)` so essentially user won't be able to type `"."`) so we have to save it in the redux form state as a string `"10." ` (previously it was a number) till user puts some valid decimal points.
But the Field component doesn't re-render because the ConnectedField uses deepEqual in its shouldComponentUpdate and deepEqual is doing `if (obj == other) return true` instead of `if (obj === other) return true` and in JS `("1." == 1) === true`(I thought we've all read the [JavaScript: The Good …

deepEqual fix so it doesn't treat 1 and 1. as equal

---

src/__tests__/reduxForm.spec.js
src/handleSubmit.js
src/reduxForm.js
src/selectors/__tests__/isInvalid.spec.js
src/selectors/__tests__/isValid.spec.js
src/selectors/isValid.js

Fixes #2244 and addresses a comment left by @orfjackal in `handleSubmit.js`.
The problem was that it should still try to submit even if previous submission errors exist. Now it will only not submit if sync or async errors exist.

Allowed submitting when submit errors exist

---

src/reduxForm.js

When `asyncValidation` failed during form submit `handleSubmit` returns rejected promise with validation errors. In this case `this.submitPromise` isn't cleared and all subsequent calls to `submit` silently stop working.

clear this.submitPromise on submit rejection

---

src/__tests__/reducer.initialize.spec.js
src/reducer.js

Analogous to the fixes for #2142, this fixes an issue with persisting existing errors across initialization.

Persist errors through the initialize action

---

docs/api/ReduxForm.md
examples/wizard/src/WizardFormFirstPage.js
examples/wizard/src/WizardFormSecondPage.js
examples/wizard/src/WizardFormThirdPage.js
src/reduxForm.js

The [wizard form](http://redux-form.com/6.3.1/examples/wizard/) is currently broken because of a change in 6.2.1 (specific PR here: https://github.com/erikras/redux-form/pull/2113). Bug report, with repro-steps: https://github.com/erikras/redux-form/issues/2231. 
When `destroyOnUnmount` is set to `false` it will no-longer unregister fields as components unmount, but it will keep the store's data, and so it will try to validate against fields that have, potentially, been unmounted and are not visible to the user. This PR introduces a new `prop` that will let you force the unregistration of fields. I was hesitant to add another prop, but I can't see a cleaner way of doing it, without re-introducing the bug that #2113 was trying to solve.
I updated the docs and the wizard form example as …

Force unregister fields

---

src/reduxForm.js

Resolves #1901 
Starting from changes in #1992, the first run of validate function receives undefined (in v6.2.0) or empty object(since v6.2.1) if ```enableReinitialize``` option is true.
This caused "Cannot read property 'xxx' of undefined" kinda errors in implementation based on v6.1.1 or before.

First call of validate always receives undefined/empty object when enableReinitialize:true

---

package.json
src/__tests__/createReduxForm.spec.js
src/createReduxForm.js

react-redux v5 was just released.
It has a backwards compatible api with v4 so should just work out of the box.

Allow react-redux v5 as a peer dependency

---

docs/api/FormSection.md
src/ConnectedField.js
src/FormSection.js
src/__tests__/Field.spec.js
src/__tests__/FormSection.spec.js

When `FormSection` needs to wrap its children in a component, you may now:
* Specify the type of component, e.g. `div`, `section`, etc.
* Pass through props, e.g. `className`, `style`, to said component
Closes #2271 and #2274.

Improved FormSection wrapper component

---

src/selectors/__tests__/isValid.spec.js
src/selectors/isValid.js

Hi,
This change https://github.com/erikras/redux-form/commit/d84aa7f055f54ed7a7e0c1eabc7b5b1ec769d331 introduced regression in using `isValid` as selection http://redux-form.com/6.3.1/docs/api/Selectors.md/
Trying to use:
`valid: isValid('myForm')(state)` 
will cause `TypeError: getFormState is not a function`

restore default value for getFormState removed in d84aa7

---

src/ConnectedField.js
src/ConnectedFields.js
src/Field.js
src/Fields.js
src/__tests__/createFieldProps.spec.js
src/createFieldProps.js
src/structure/immutable/index.js
src/structure/plain/index.js

cb3abb5b41976458fc0c54246df2eeea1f538d34 added functionality that merged the state into the meta object for fields. However, when using Immutable JS structures the state will be an Immutable.Iterable. When developing in React Native the `Object.assign` call here https://github.com/erikras/redux-form/commit/cb3abb5b41976458fc0c54246df2eeea1f538d34#diff-7eb826f425b082db29894569d83899f8R68 causes an exception as described in #1877 and #1955.
```
One of the sources for assign has an enumerable key on the prototype chain. This is an edge case that we do not support. This error is a performance optimization and not spec compliant.
```
I am assuming this is because the Object.assign polyfill is different in the React Native environment (any confirmation on this?). I tested the webpack polyfill …

Ensure state is merged into meta props as plain object (#1877, #1955)

---

docs/api/Selectors.md
src/createAll.js
src/index.js
src/selectors/__tests__/getFormAsyncErrors.spec.js
src/selectors/getFormAsyncErrors.js

It was requested in #2201 but was never implemented. The implementation and tests are pretty much similar to `getFormSyncErrors` unless I'm missing something. Tested on the application I'm working on.

Implement `getFormAsyncErrors` selector

---

src/__tests__/reducer.change.spec.js
src/structure/plain/deleteIn.js

If I have a form with field array and if I set error to the field array an exception will be thrown every time I change any field in the array.  This is a test that fails in such a situation. [issue](https://github.com/erikras/redux-form/issues/2323)

Exception thrown if server returned submit error for fieldArray

---

docs/api/Field.md
src/ConnectedField.js
src/Field.js
src/__tests__/Field.spec.js

Introduces new `onBlur`, `onChange`, `onFocus`, `onDragStart`, and `onDrop` callback props that can be given to `Field`, which also provide `event.preventDefault()` functionality to cancel events triggering Redux actions.
Fixes #2334.

Event Callbacks

---

docs/api/ReduxForm.md
src/__tests__/handleSubmit.spec.js
src/__tests__/reduxForm.spec.js
src/handleSubmit.js

Completes #2394 
In some situations it would be helpful to have access to the props on the component during the onSubmitSuccess and onSubmitFail callbacks. This PR passes them in on those callbacks.

Add Props to onSubmitSuccess and onSubmitFail

---

docs/api/Selectors.md
src/__tests__/actions.spec.js
src/__tests__/reducer.destroy.spec.js
src/actions.js
src/reducer.js
src/selectors/__tests__/getFormNames.spec.js
src/selectors/getFormNames.js
src/structure/immutable/__tests__/keys.spec.js
src/structure/immutable/index.js
src/structure/immutable/keys.js
src/structure/plain/__tests__/keys.spec.js
src/structure/plain/index.js
src/structure/plain/keys.js

* Allowed multiple form names to be passed to `destroy()` action creator.
* Created `getFormNames(state)` selector
Fixes #2397.
Allows for fun stuff like:
```jsx
import { getFormNames, isDirty } from 'redux-form'
const dirtyForms = getFormNames()(state).filter(form => isDirty(form)(state))
```

Multi-destroy and getFormNames selector

---

src/structure/immutable/index.js

Currently `structure.getIn` breaks when using Immutable `Record`s or other keyed Immutable objects that aren't `Map`s or `List`s, because it tries to use the `plainGetIn` on those.
I've tested this fix in the context of an app I'm working on and these changes work in my case, but haven't verified with any actual tests. By definition all `Iterable`s have `getIn` so I think it's a low risk change, at least one that's guaranteed to not break any existing desired behaviours with `Map`s and `List`s.
The symptoms are that `ConnectedField`s are unable to find the field's values in state and `value` is subsequently passed down as an empty string.

Choose getIn based off Iterable.isIterable()

---

docs/api/ActionCreators.md
src/__tests__/reducer.initialize.spec.js
src/actions.js
src/reducer.js

My proposed solution to #1994 
Also, I made it possible to pass `keepDirty` in the same options argument as `keepSubmitSucceeded` is passed in, for the sake of cleanliness, but I preserved backwards compatibility.

feat(initialize): add keepSubmitSucceeded option

---

docs/api/Field.md
docs/api/FieldArray.md
src/__tests__/generateValidator.spec.js
src/generateValidator.js

Currently, the API for `validate` passed to `config` allows props to be
accessible by validation rules. The same should be done for field-level
validations. This PR provides props passed to the form as the second argument
of the function returned by `generateValidator()`, making the APIs between the
two forms of validation consistent.
Refers to #2430

Provide validation functions with access to form props

---

src/__tests__/reduxForm.spec.js

References #2431.
* Added `warnIfNeeded()` tests based on `validateIfNeeded()`
* Added a test to check if values and props are correctly passed to `validate` & `warn`
I'm not sure my method for checking props is the most elegant (spying on the props passed to `shouldValidate` and comparing with the argument of `validate` with `Object.keys()`) but I couldn't find a state where the props had the exact same values as well.
Let me know if I missed anything, thanks!

Add more tests for validateIfNeeded & warnIfNeeded

---

docs/api/Selectors.md
src/__tests__/immutable.spec.js
src/__tests__/index.spec.js
src/createAll.js
src/immutable.js
src/index.js
src/selectors/__tests__/getFormInitialValues.spec.js
src/selectors/getFormInitialValues.js

This seemed like an important missing selector. While a user of redux-form will usually have access to the initial values they passed in one way or another, exposing a selector for them can make it easier to hook into redux-form with epic, thunks, and sagas (invoking the selector on getState()) and keep business logic out of the component.
I'd be happy to describe a specific use case if desired.

Add initial value selector

---

docs/api/Field.md
docs/api/FieldArray.md
docs/api/Fields.md
src/ConnectedFieldArray.js
src/Fields.js
src/__tests__/Field.spec.js
src/__tests__/FieldArray.spec.js
src/__tests__/Fields.spec.js
src/__tests__/createFieldArrayProps.spec.js
src/createFieldArrayProps.js
src/util/__tests__/prefixName.spec.js
src/util/prefixName.js

Breaking change: Change `Fields` `names` instance API to return `FormSection` prefixed names, to be consistent with `Field` and `FieldArray`.
Breaking change: Change instance API documentation of `Field`, `Fields` and `FieldArray` `name` and `names` to match the behavior of the code with regards to `FormSection`, which is to return the `FormSection` prefixed `name` and `names`.
In `FieldArray`, `fields` `map`, `forEach` and `reduce` now call back with unprefixed name, as the prefix is added in `Field` and `Fields`. Fixes #2121.

FormSection fixes

---

docs/api/FieldArray.md
src/ConnectedFieldArray.js
src/__tests__/FieldArray.spec.js

Document FieldArray fields.name prop.

Remove undocumented name, validate and warn from FieldArray props.

---

src/__tests__/Field.spec.js
src/__tests__/FieldArray.spec.js
src/__tests__/Fields.spec.js
src/__tests__/FormSection.spec.js
src/__tests__/actions.spec.js
src/__tests__/reducer.initialize.spec.js
src/__tests__/reducer.registerField.spec.js
src/__tests__/reducer.unregisterField.spec.js
src/__tests__/reduxForm.spec.js
src/actions.js
src/reducer.js
src/reduxForm.js
src/selectors/__tests__/isInvalid.spec.js
src/selectors/__tests__/isValid.spec.js
src/selectors/isValid.js
src/structure/immutable/__tests__/setIn.spec.js
src/structure/immutable/expectations.js
src/structure/immutable/index.js
src/structure/immutable/setIn.js
src/structure/plain/__tests__/setIn.spec.js
src/structure/plain/expectations.js
src/structure/plain/index.js

For backward compatibility, when registration count is one, the registeredFields will not have the count property. Undo #2040. Fixes #2016, #2223, #1705. Partially fixes #1990.

Keep track of registration count in registeredFields

---

src/__tests__/reduxForm.spec.js
src/reduxForm.js

as it causes its entry in storeState.fields to become an object instead of an array. The ARRAY_* reducers expects the fields entry to be an array. Fixes #2014.

Do not set FieldArray as touched on submit

---

src/reduxForm.js

reduxForm.js ShouldComponetUpdate now uses this.props.pure instead of config.pure to decide whether to not update.
Fixes #2567.

Fix for issue 2567

---

examples/normalizing/src/FieldNormalizingForm.js

Here is the steps for represent this bug:
1. Open [http://redux-form.com/6.5.0/examples/normalizing/](http://redux-form.com/6.5.0/examples/normalizing/)
2. Increase Max, and it will show 11
3. Increase Min
Expect:
Show 2 for Min
Fact:
Still show 1 for Min
I just did some debug and find these:
1. The field with type="number" will return a string value. So in step 2, the form value would be 
```
{
"min": 1,
"max": "11"
}
```
2. The functions `lessThan` and `greaterThan` just compare the values without parsing number 
```
const lessThan = otherField =>
(value, previousValue, allValues) => value < allValues[otherField] ? value : previousValue
const greaterThan = otherField =>
(value, previousValue, allValues) => value > allValues[otherField] ? value : previousValue
```
Solution:
1. Fixed the …

Fix value type issues in 'Field Normaizing Example' page

---

src/ConnectedFieldArray.js

This fixes what is mentioned in #2466.
Because of fixes introduced in #1578, FieldArray does not re-render when the `value` changes. However this causes the FieldArray to not render updates for swapping, insertion, or other operations on the `value`, which is undesired behaviour.

Fix shouldComponentUpdate in FieldArray

---

src/__tests__/reduxForm.spec.js
src/reduxForm.js

Was suggested and attempted in #2530.
Fixes #883.

Added form-wide onChange functionality

---

src/propTypes.js

This is currently set to `bool` whereas it is a string if a field triggers async validation.
See
http://redux-form.com/6.5.0/docs/api/Props.md/#-asyncvalidating-string-boolean-
Current PropType violation:

Update asyncValidating PropType to match documentation

---

docs/GettingStarted.md

This is a minor addition to the Getting Started docs that would have helped me immensely.  Searching on stack overflow reveals I'm not the only one who was confused by the fact that the key being passed to `combineReducers` **must be `form`**, and cannot be a custom name  (I had used `forms`!)
More details, and the answer that helped me solve my issue – http://stackoverflow.com/a/40923003/1084257
This tiny addition to the docs may help others avoid the same problem.

Getting started clarification

---

docs/api/Selectors.md
src/__tests__/immutable.spec.js
src/__tests__/index.spec.js
src/createAll.js
src/immutable.js
src/index.js
src/selectors/__tests__/getFormSyncWarnings.spec.js
src/selectors/getFormSyncWarnings.js

Added a new selector to the list: `getFormSyncWarnings` as suggested [here](https://github.com/erikras/redux-form/issues/2176). Implementation is the same as `getFormSyncErrors`.

Added selector for getFormSyncWarnings.

---

docs/api/ActionCreators.md

the `destroy` action creator is actually variadic so I updated the documentation.
This caught me off guard when updating from `6.2.0` to `6.5.0` because one of my reducers using this action type.

destroy action creator documentation was wrong

---

src/__tests__/readField.spec.js
src/readField.js

React components that take just the array field still need to re-render.
Existing tests covered this case, but explicitly asserted the incorrect
behavior.
Specifically "top-level" array fields, because array fields below the
top level change their identity based on the return value rather than
modifications to the fields object.
Copied the control flow from the object-field path, which Does The Right
Thing.

(v5) Changes to members of top-level array field should change instance identity

---

src/__tests__/reducer.arraySplice.spec.js
src/reducer.js

When adding a new field to a `FieldArray` (which already has a field with a `submitError`), the `submitError` for the new field is initialised with `empty`.
This breaks form validation, as the new field has not been submitted yet and therefore should not have an initial `submitError`.
Therefore changing the initial value for `submitError` and `asyncError` of new fields to `undefined`.
Issue: https://github.com/erikras/redux-form/issues/2667

Fix initial submitError state for FieldArrays

---

src/ConnectedField.js
src/ConnectedFieldArray.js
src/ConnectedFields.js

Use `getIn` instead of `plain.getIn` in case we're using `redux-form/immutable`.
Ref. https://github.com/erikras/redux-form/issues/2718

Fix #2718 (Incorrect way of accessing syncErrors, syncWarnings in ConnectedField, ConnectedFieldArray, ConnectedFields for redux-form/immutable)

---

src/hasError.js

Because of using `plain.getIn`, the syncErrors are not respected during the form submit operation and form is submitted even if it is not valid.
Can we release it ASAP?

Fix: hasError used plain.getIn(syncErrors, key) for Immutable instead of getIn(syncErrors, key)

---

docs/api/ReduxForm.md
src/__tests__/Form.spec.js
src/__tests__/reduxForm.spec.js
src/reduxForm.js

This enables common use cases such as submitting the form on change, and
specifically re-using the same action for submit and change.

Change the form-level onChange to accept the same args as onSubmit

---

src/FieldArray.js
src/__tests__/FieldArray.spec.js

I am trying to implement some interface that is similar to http://redux-form.com/6.4.3/examples/selectingFormValues/ but fields should be wrapped into `FieldArray`.
Currently, this is not possible, because `shouldComponentUpdate` prevents all further updates, even they are possible. See added test, it didn't passed before, but currently it passes.

Allow FieldArray to be impure

---

examples/wizard/package.json
examples/wizard/src/WizardForm.js
package.json
src/ConnectedField.js
src/ConnectedFieldArray.js
src/ConnectedFields.js
src/Field.js
src/FieldArray.js
src/Fields.js
src/Form.js
src/FormSection.js
src/propTypes.js
src/reduxForm.js

React 15.5+ warns when using `React.PropTypes`. This PR updates the source to use instead the `prop-types` package as suggested in https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html.

Migrate from React.PropTypes to prop-types

---

src/reduxForm.js

instead of referring to a possibly stale reference to validExceptSubmit, refer to this.props.validExceptSubmit... opened an issue /w more details here: #2785

fix (possibly stale) reference to validExceptSubmit variable

---

examples/fieldArrays/src/FieldArraysForm.js
src/__tests__/FieldArray.spec.js
src/createFieldArrayProps.js

Fixes #2830.
It had never ever been set to anything, was never documented, and was only causing confusion.

Remove meta.touched prop from FieldArray

---

examples/fieldLevelValidation/src/FieldLevelValidation.md

Summary:
-----
Field level validation functions take 3 params -> `(value, allValues, props)`.
This is accurately documented in the API documentation: http://redux-form.com/6.6.3/docs/api/Field.md/#-validate-value-allvalues-props-error-optional-
However, the Field-Level Validation example only documents 2 params (http://redux-form.com/6.6.3/examples/fieldLevelValidation/).
Changes:
------

Add missing props param in the field-level validations example documentation

---

docs/api/SubmissionError.md

I was having a hard time finding the documentation on what the difference between the field name and the _error prop for SubmissionError. This adds the language used from the onSubmit documentation about SubmissionError

Improve submission error docs

---

docs/api/Selectors.md
src/__tests__/immutable.spec.js
src/__tests__/index.spec.js
src/createAll.js
src/immutable.js
src/index.js
src/selectors/__tests__/getFormMeta.spec.js
src/selectors/getFormMeta.js

Same as other selectors, but returns the slice form.${formName}.fields of state. Can be useful f.e. for [#2585](https://github.com/erikras/redux-form/issues/2585)

Add a selector to get touched and visited props from state

---

src/__tests__/reduxForm.spec.js
src/reduxForm.js

Fixes #2838.
The `this.lastSyncErrors` logic added in #2797 was flawed.

Fixed field-level validation reset bug

---

src/deleteInWithCleanUp.js

This is related to #2875. I'm not sure if this is the best way of fixing the issue, but it solves the problem atleast. Adds a check to see if there is anything in the state before calling `deleteIn` when `deleteInWithCleanUp` is called. With this code I no longer get `Invalid KeyPath` errors when using Immutable.js and editing FieldArrays after submit has failed.

deleteInWithCleanUp needs to check if there is a value in the state before deleting.

---

src/events/__tests__/getValue.spec.js
src/events/getValue.js

instead true/false to be true/'' as the current true/false breaks pristine prop - problem described here: https://github.com/erikras/redux-form/issues/2857

Checkbox default behavior proposal

---

src/structure/immutable/__tests__/deepEqual.spec.js
src/structure/immutable/deepEqual.js

Fixes issue #2882. Deep equal wasn't checking to see if the key exists on the map it was comparing itself to.

Fix deep equal on maps with different structures

---

docs/api/Props.md
src/__tests__/reduxForm.spec.js
src/createReduxForm.js

Fixes #2901.
Although this does add an additional form rerender. It will only ever happen once during the form's lifecycle.

Added initialized prop

---

docs/api/FieldArray.md

There are three parameters that get passed, not two. Anyways, to make it less prone to be out of date, changed the wording to "following parameters".

Fix minor incorrect doc sentence

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

Using the new `Form` wrapper, I catch a problem that if you're using the wrapper but you want to use the native submit passing `onSubmit` into config param, will enter in a stack trace.
Here a code example:
```
import {Form} from 'redux-form';
class MyComponent extends React.Component {
render() {
const {handleSubmit} = this.props;
return (
<Form onSubmit={handleSubmit}>
<input type="submit" value="aaa" />
</Form>
);
}
}
reduxForm({
form: 'test',
onSubmit: (value) => value
})(MyComponent);
```
I just added a verification to not call `innerSubmit` if is already the `submit` function.

Submit - Avoid strack trace using native submit

---

src/createReduxForm.js

initialValues can be an array or an object.  For example a form with fields: 
`<Field name="0.firstName />
<Field name="1.firstName" />`

updated PropTypes for initialValues to support an array or an object

---

docs/api/README.md

Fixing an extraneous _to_ that was squirreled away under the descriptive text for `Fields`.

Correct grammatical error in API README.md

---

src/__tests__/immutable.spec.js
src/__tests__/index.spec.js
src/propTypes.js

Otherwise we get errors on use, e.g.:
```
Failed prop type: inputField: prop type `meta` is invalid;
it must be a function, usually from React.PropTypes.
```

Fix fieldPropTypes to have shapes for input and meta

---

src/__tests__/immutable.spec.js
src/__tests__/index.spec.js
src/immutable.js
src/index.js
src/propTypes.js

These propTypes are those for the form component and labelling them as such
disambiguates the variable for all importers, saving them from having to
redefine the name 'as' something in the base case.

Export formPropTypes as an alias for propTypes

---

src/immutable/getFormAsyncErrors.js
src/immutable/hasSubmitFailed.js

I'm not quire sure if this is bug or not because i'm not using this selectors for anything, but I'm assuming that they should use `immutable` structure like other selectors. 
I ran on it while debugging issue from this PR https://github.com/erikras/redux-form/pull/3022

use immutable structure for selectors

---

src/structure/immutable/__tests__/keys.spec.js
src/structure/immutable/keys.js

Reason for this change is that for immutable structure `valid` prop  from `reduxForm()` is always `false` 
That is happening because `isValid` selector in this place
https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L705
is using `getFormState` that returns plain object so `registeredFields` here
https://github.com/erikras/redux-form/blob/master/src/selectors/isValid.js#L36
are plain object and `keys(registeredFields)` returns empty list from https://github.com/erikras/redux-form/blob/master/src/structure/immutable/keys.js#L3
After this change it seams to work as expected.

add support for plain objects in keys extractor from immutable structure

---

src/ConnectedField.js

When you pass a value to a Field's Component's onChange, ConnectedField passes that raw value as the event.
Using the Field's `onChange` or other handler overrides lets us `event.preventDefault()`, but if the event is a value, we get an error.
This does a safety check before calling `event.preventDefault()`.

Add safety checks for events in ConnectedField

---

docs/api/ReduxForm.md
src/__tests__/reduxForm.spec.js
src/createReduxForm.js

Background:
Sometimes, a prop might be a POJO that contains a nested immutable structure. Draft-js' `editorState` is a great example. Within sCU, the plain `deepEqual` function is used on it & breaks. 
Why this is needed:
- Per #2798 the only way to make this work with draft-js is to serialize the editorState.
- The beauty of immutables is that we don't have to do a deep equals, comparing references is enough
- folks may use different immutable libraries so there is no safe way to ducktype an immutable
- folks may have large POJOs that they want to exclude from being deep equaled in sCU. This is a cheap, unobtrusive way to add performance. 
Example:
`reduxForm({form: 'linkChanger', immutables: ['editorState']})`
can bump the docs if you like it

add support for props with nested immutables

---

docs/GettingStarted.md

Because we reassigned value to ContactForm later by wrapping it with reduxForm().

changed const to let on line 73

---

examples/immutable/src/ImmutableForm.js
examples/immutable/src/warn.js

Had a discussion a while back in #2258 where there was some confusion regarding using `warn` in immutable forms, and thought this might help to reduce future confusion.
However I haven't verified my changes yet because of the issues described in #3041 and #3038.

Add `warn` to Immutable demo form

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

This parameter may be undefined, as all configs can be defined via props.
Fixes #3048

Don't use initialConfig when checking immutableProps

---

docs/GettingStarted.md

The getting started docs have an error! This fixes it up for users who might blindly copy-paste the example code (like I did 😆 ). Using `let` to declare the `ContactForm` component will allow it to be reassigned further down in the example.

Fix assignment error in Getting Started docs

---

src/__tests__/reducer.unregisterField.spec.js
src/createReducer.js

Currently errors will be cleared every time an `UNREGISTER` action is fired even if the count is greater than 1.
This would cause the errors to get cleared even when there is still a form field on the page.
_you can see a demo of the error [here](https://codesandbox.io/s/ADjL8EGD1)_
This PR changes the behavior so that errors will only be cleared if the count is <= 0 and the field is actually being removed from the `registeredFields`

Do not clear errors unless field is being removed from the form

---

src/createReduxForm.js

I noticed that my form and its fields were unnecessarily re-rendering upon any changes to my store. I realized that React Redux's shallow comparison was failing when comparing `syncWarnings` between states. This is because Redux Form's connector returns a new object every time when there are no `syncWarnings` or `syncErrors`.
Changing this code to use the `empty` object makes shallow comparison work properly, reducing unnecessary re-renders significantly.

Use same empty object for syncErrors and syncWarnings

---

src/__tests__/reducer.stopAsyncValidation.spec.js
src/createReducer.js

Fixes https://github.com/erikras/redux-form/issues/2953
The reason this makes sense to do, is that the field specific asyncErrors are cleared already by events like CHANGE, so it's not necessary to clear all asyncErrors in the STOP_ASYNC_VALIDATION action.
This allows us to have more than one field with async validation in the same form. When one field fails async validation but then another field passes, it no longer clears asyncErrors for the whole form, therefore setting the first field to a valid state incorrectly.

Don't clear all asyncErrors on stopAsyncValidation

---

package.json

Redux-form creates a duplicate react install in react-native due to the React 15 peer dependency
Taken from [react-redux](https://github.com/reactjs/react-redux/blob/master/package.json#L112)
Tested on React Native 45
Ciaran

Extend React Peer dependency to version 16

---

src/__tests__/reducer.initialize.spec.js
src/createReducer.js

Hi, I made this fix for #3095.
It prevents the initialize action with keepDirty set to true to create 'empty objects' `{}` uselessly if the field to keep pristine has to change to `undefined`. This happens because of the `setIn` function that creates all the objects required for the nested path.
Example : the initialize action in the new test sets the value of `myList.0.myField` to same as the one in `{myList: []}`.
Before the fix, it created an empty object in the values `{myList: [{}]}`, which for ReduxForm is the same as `{myList: [{myField: undefined}]}`.
Now it leaves the values like this `{myList: []}`

Fix initialize with keepDirty and empty array creates an empty object in form values (#3095)

---

src/__tests__/Field.spec.js
src/createField.js

This will ensure that changes to these functions are reflected in form
validation. Achieved by re-registing the Field with reduxForm when new
validate or warn props are recieved.
See issue: https://github.com/erikras/redux-form/issues/3012

Handle changes to Field validate/warn props

---

examples/asyncValidation/src/AsyncValidation.md
examples/asyncValidation/src/AsyncValidationForm.js
examples/asyncValidation/src/asyncValidate.js
src/createReducer.js

Reverts erikras/redux-form#3134
I changed my mind. It shouldn't do this, as this means there is no good way to _clear_ an async validation error.
The field-level async validation that #3134 was moving towards will require a separate action to set the errors.

Revert "Async validation support for multiple fields"

---

docs/api/FormValueSelector.md

Might help others avoid a bit of confusion like I encountered in #3184.

Docs: Add note indicating that FormValueSelector can only be used as mapStateToProps if selecting multiple fields

---

src/propTypes.js

The `custom` object is not included in the props given to a decorated form component; instead custom props are included directly in the props object. As `custom` is nevertheless marked with `isRequired` in `fieldPropTypes`, the proptype isn't actually usable as it'll always fail.

Remove custom prop from fieldPropTypes

---

src/createReduxForm.js

This is a bug found whilst investigating #3196.
Even when using `redux-form/immutable`, the sync errors and warnings are plain javascript objects.

Sync warnings and errors should default to {}

---

docs/api/ReduxForm.md

The comparison is with deepEquals, so I believe "shallowly" is a documentation error.  This added to confusion in #2833.

Remove 'shallowly' in `pure` prop docs

---

docs/api/Field.md

Documentation for #3094, #3211.

Add note on validate/warn prop re-registering

---

src/index.js.flow

This is a fix for #3278 .
The bug is detailed in the issue. (thanks @aloker )

fix #3278 (incorrect flow type declarations)

---

docs/api/FieldArray.md

Adding docs for https://github.com/erikras/redux-form/blob/0183d43a19e52815e1b7870ac4f7ddd719ad97c7/src/createFieldArrayProps.js#L22
This property is already used in the fieldArray example, as pointed out in #3123

Docs: add meta.submitFailed to fieldArray

---

src/__tests__/handleSubmit.spec.js
src/handleSubmit.js

re-submitting a form that was invalid and untouched with async errors would swallow async errors in onSubmitFail.
refer: https://github.com/erikras/redux-form/issues/1367
cc @erikras @danielrob @gustavohenke

don't swallow async errors when the form is not valid

---

src/createFormValues.js
src/createReduxForm.js
src/util/getDisplayName.js

I never used Flow before, so I have no idea whether this is correct or not 😃 
I just started a trial and error game until the warnings disappeared and no errors were spilled by `npm run test:flow`
Fixes #3385

Don't use "import * as React" to avoid deprecation warnings

---

docs/api/Field.md
src/__tests__/generateValidator.spec.js
src/generateValidator.js

See https://github.com/erikras/redux-form/issues/3350

Add name parameter for field level validator

---

docs/faq/BundleSize.md

There is only one single default export in the actions source code, so there is no need to use a multi-import alias.
https://github.com/erikras/redux-form/blob/0b49d4349f008a0458b0fa0a6b5cee10bc3e2b0a/src/actions.js#L440

Remove unnecessary import alias in BundleSize.md

---

src/createReduxForm.js

Pretty small fix for #2626 and #2230
Fixes #2626, fixes #2230

Hoist static fields of the Wrapped Component

---

src/__tests__/immutable.spec.js
src/__tests__/index.spec.js
src/immutable.js
src/immutable.js.flow
src/index.js
src/index.js.flow
src/propTypes.js

Add FieldArray PropTypes for the user's convenience.
Closes #2447 
Basic Usage
``` js
import { fieldArrayMetaPropTypes, fieldArrayFieldsPropTypes } from 'redux-form';
class MultiClientSelectForm extends React.Component {
// do FieldArray react conmponent stuff
}
MultiClientSelectForm.propTypes ={
fields: fieldArrayFieldsPropTypes,
meta: fieldArrayMetaPropTypes
}
```

Add FieldArray propTypes close #2447

---

docs/api/FormValues.md
src/__tests__/formValues.spec.js
src/createFormValues.js

We run into a situation where we needed to retrieve a form field value of a form field with a dynamic name (form field name needs to be created by using variables available in props). To handle this in an appropriate way, we suggest to also accept functions as a first argument of the formValues hoc which will resolve the according form field values (where the name was created dynamically, using variables stored in props).
A short example: `formValues((props) => ({ myFormFieldValue: props.formFieldName }));`
Feature has been implemented, docs and unit tests have been updated.

Support for dynamic form values in form values hoc

---

.travis.yml
package.json

The thing is that `prepublish` currently runs:
- npm run test 
- npm run test:flow 
On top of `prepublish` Travis also runs
- npm run lint
- npm test
- npm run test:cov
- npm run test:codecov
(so test is running 3 times currently on CI...).
Would make more sense (and speed up travis a lot up) if `prepublish` ran:
- npm run lint
- npm run test:flow 
- npm run test:cov
And Travis additional step ran
- npm run test:codecov

Simplify travis and prepublish build

---

src/ConnectedField.js

When using onChange in React Native, the users are faced with a couple possible error messages, as seen in #3153 and #3238.
This is due to the fact that it doesn't seem to be possible to properly extends React Native's event ( https://github.com/facebook/react-native/issues/5507). My proposal is to skip adding .preventDefault to TextInput's onChange's event.
No test was broken
Linting was respected
Closes #3153, closes #3238

Skip adding preventDefault to onChange events in React Native

---

package.json
src/ConnectedField.js

The main purpose of this PR is to add the same logic that PR #3460 (which was merged) added to `onChange` also to `onBlur` and `onFocus`.
I've also edited a dev-dependecy line of package.json:
```diff
-"immutable": "^4.0.0-rc.3",
+"immutable": "4.0.0-rc.3",
``` 
This was necessary to prevent the test suite to fail miserably with 21 errors (all of them are `immutable`-related). This isn't a solution to #3493, but it's needed to mark the fact that versions `4.0.0-rc.>3` of `immutable` aren't supported as of now. I hope this doesn't add to much noise to the PR @erikras.

Extends PR #3460, also locks immutable version

---

src/createReduxForm.js
src/util/isHotReloading.js

This PR only destroys the form on unmount when there is not a hot reload in progress. This is currently webpack HMR specific.
A similar fix was suggested in #947 but this PR fixes the behavior only during a hot update, not in the presence of hot reloading capabilities. @gaearon suggested not to do this but since react-hot-loader@3.x seems dead and this issue has been around for a while with redux-form and is very frustrating to deal with I think it is worth fixing it with this workaround.
There are some flow errors that I'm really not sure how to fix. I also don't know how to create tests that are useful since it requires overriding the global `module`.
Fixes #623 
Fixes #2826 
Fixes #3005.

Fix hot reloading destroying form

---

src/propTypes.js

In case errors are passed as something different than strings(e.g.: `<FormattedMessage />` when using react-intl)

Changed meta prop type to any

---

docs/api/ReduxForm.md
src/__tests__/reduxForm.spec.js
src/createReduxForm.js

It would be useful to know which field has changed in the `onChange` handler. Rather than bothering to compute this itself, redux-form can just send along the previous form values as an additional argument to the `onChange` handler.
One use case for this is an onChange handler that auto-submits the form values when one has changed.

Include previous form values to onChange handler

---

package.json

Upgraded single package to the latest version
should not have any breaking changes

update hoist-non-react-statics version for v5

---

docs/api/ActionCreators.md
src/ConnectedFieldArray.js
src/__tests__/actions.spec.js
src/__tests__/createFieldProps.spec.js
src/__tests__/helpers/reducer.clearFields.js
src/__tests__/reducer.spec.js
src/__tests__/reduxForm.spec.js
src/actionTypes.js
src/actionTypes.types.js.flow
src/actions.js
src/actions.types.js.flow
src/createReducer.js
src/immutable.js

`clearFields(form:String, keepTouched: boolean, persistentSubmitErrors: boolean, ...fields:String)`
Cleans fields values for all the fields passed in.
> If the `keepTouched` parameter is `true`, the values of currently touched fields will be retained
> If the `persistentSubmitErrors` parameter is `true`, the values of currently submit errors fields will be retained
Closes: #3055, Closes: #2224

Add cleanFields action

---

src/createReduxForm.js

React 16 ensures a certain order of lifcecycles when replacing a
component which causes redux-form to destroy the form, breaking
it. This change, when used with `enableReinitialize`, causes the
form to reinitialize correctly, preserving the form.
this pr address https://github.com/erikras/redux-form/issues/3435
this is probably going to fail a lot of tests, but want to start the 
conversation as to what is needed for redux-form to work with
React 16

move initialization to componentDidMount

---

docs/api/ActionCreators.md
docs/api/ReduxForm.md
src/__tests__/helpers/reducer.initialize.js
src/createReducer.js
src/createReduxForm.js

I struggled a lot after working with dynamic fields. I figured out, that the fields have to be registered in order to get the (initial) values updated if keepDirty.
The problem is, that I got fields which will register after the initialising happens. Just initialising again doesn't solve the problem, because the first initialise did mutate the initialValues, which will be  dirty in the second case and will not update because of this.
After this change, the logic for updating pristine fields will now always apply, no matter if the fields a registered or not. This may be breaking to some apps? But I think this is more expected then the other case?
Does this make any sense to you @erikras ?
Thanks

Update non dirty values also for non registered field values

---

src/ConnectedField.js
src/ConnectedFields.js
src/__tests__/reduxForm.spec.js
src/createReduxForm.js
src/defaultShouldAsyncValidate.js
src/types.js.flow

Currently, `asyncValidate` can only be run `onBlur`. This PR provides support for running it `onChange` as well.
This introduces an `asyncChangeFields` property to the `reduxForm()` API. Since the default functionality of `asyncBlurFields` is to run the validator on *all* fields if that property is not passed to the `reduxForm()` constructor, I kept that the same for `asyncChangeFields`. However, this introduces some potentially unwanted behavior: providing an `asyncValidate` function but neither `asyncChangeFields` nor `asyncBlurFields` props to `reduxForm()` will cause `asyncValidate` to run on both blur and change for all fields. I'm not sure this is desirable, and @danielrob [doesn't want](https://github.com/erikras/redux-form/issues/3521) to turn on async validation for on change …

Support async validation on change

---

src/selectors/__tests__/getFormMeta.spec.js
src/selectors/__tests__/getFormSubmitErrors.spec.js
src/selectors/__tests__/getFormSyncErrors.spec.js
src/selectors/__tests__/getFormSyncWarnings.spec.js
src/selectors/getFormMeta.js
src/selectors/getFormSubmitErrors.js
src/selectors/getFormSyncErrors.js
src/selectors/getFormSyncWarnings.js

feature/ValidSelectorsTypes fixes return Selectors types (Typesafe selectors #3099)

---

src/immutable.js
src/index.js

Since #2827 is not implemented I have written code around it by using the `updateSyncWarnings`-action from the library to manually update warnings after doing an async call. However, this action is not currently exported from the library, so instead of just doing `import { updateSyncWarnings } from 'redux-form'` I have to do `import actions from 'redux-form/lib/actions'`.

Export updateSyncWarnings action

---

docs/Flow.md

It's not clear from the docs that the types will not import when the `node_modules` folder is ignored inside `.flowconfig`, which is recommended sometimes in the community and can cause trouble in this case.
This commit adds clarification on how to avoid the case where Flow can't find the type definition for `redux-form`.

Include troubleshooting instructions for Flow.

---

src/__tests__/Field.spec.js
src/createReduxForm.js

Check if either asyncBlurFields or asyncChangeFields are provided. If neither is, trigger validation. If any is, need to check if the blurred/changed field is on the corresponding list.
Fixes #3645

Fix asyncValidate when asyncBlur/ChangeFields are provided

---

src/types.js.flow

The name parameter is officially documented as part of the API but is missing from the Validator type definition.
BTW, I don't think it makes much sense to have `any` marked as a *maybe* type since `any` already implies it can be anything ;) But that's unrelated so I didn't change it.

Add missing "name" parameter to Validator function type.

---

src/__tests__/FieldArray.spec.js
src/createReduxForm.js

Empty `lastFieldValidatorKeys` when  no field level validators were found. This allows `validateIfNeeded` to detect when a previously emptied FieldArray has an item added back.

Fix field-level validation on previously emptied FieldArray

---

package.json

es6-error in version 4.1.0 has an error and due of this redux-form doesn't show errors. 
An instance of SubmissionError class doesn't recognize as its class. 
```
const error= new SubmissionError({...});
error instanceof SubmissionError // gives false but should true
```
No issue with module es6-error@4.1.1. 
Unfortunately even there is never version of es6-error, yarn on my production server still installs broken version which is 4.1.0.

Update es6-error module

---

docs/api/ActionCreators.md
src/index.js

[Closes #3708] Bug/clear async errors

---

src/createReduxForm.js

Fixes https://github.com/erikras/redux-form/issues/3303
In the very likely case that an error is encountered during a submit callback we need to be able to reliably detect any failures.
This restores the correct behavior stated in the [documentation](https://redux-form.com/7.2.0/docs/api/reduxform.md/#-code-submit-promise-code-):
> Submits the form. [You'd never have guessed that, right?] Returns a promise that will be resolved when the form is submitted successfully, or rejected if the submission fails.
This will revert the change made in https://github.com/erikras/redux-form/pull/3227, but throwing the error is a _far better_ compromise that benefits a _much larger set_ of redux-form users. It's possible to silence errors in your own code, but not possible to recover discarded errors …

Ensure errors thrown from submit handler are not silenced

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

Fixes https://github.com/erikras/redux-form/issues/3658
Also added some variations to an existing test to verify the change. The new tests will fail without the code change.

fix submit crashing when asyncBlurFields or asyncChangeFields is given

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

fix #3688 
fixed by keeping a reference count of names registered with `ReduxForm.register`/`unregister`, just like the reducer keeps a reference count of fields.

fix validation after duplicate field unmount

---

examples/fieldLevelValidation/src/FieldLevelValidation.md

In this commit message, I'm using the word "aside" as a noun (as in, "She wrote it as an aside"), not as an adverb (as in, "She set her notes aside").

Delimit aside using parentheses instead of comma

---

src/__tests__/Field.spec.js
src/createField.js
src/util/shallowCompare.js

This PR fixes a regression introduced in #3138 where the `shouldComponentUpdate` method of `createField.js` no longer sent `nextState` as an argument to `shallowCompare` when checking if a component should update. This regression effectively made every field re-render every time since the default state of a react component is `null` and an unspecified argument is `undefined`, making `shallowCompare` do a `null === undefined` check to determine if the component should update.

Fields re-render every time due to regression introduced with flow typings.

---

src/handleSubmit.js

Following this [issue](https://github.com/erikras/redux-form/issues/3636), I added a `console.error` to get the expected behavior  
Is it ok ? I have the impression that I didn't understand well the bug, cause it's normal that the error get swallowed as it's thrown in a promise

Log onSubmitSuccess thrown errors

---

src/ConnectedField.js

asyncErrors & submitErrors are flat key-value objects: `{ 'field.a.b.c': 'error' }`, so we should escape field name in order to get data from it.

Fix async/submit errors getter for nested fields

---

src/structure/immutable/__tests__/setIn.spec.js
src/structure/immutable/setIn.js

This PR fixes an issue introduced in #3692 where the `mergeLists` method in `setIn.js` for `immutable.js` was updated due to `mergeDeepWith` being removed as a `List` function in `immutable.js@4.0.0-rc.5`. Unfortunately this change introduced and error in which arrays with more than 32 elements were behaving unexpectedly since the new way of doing it didnt use ordered maps, instead just calls `toMap()`, which causes the merging to lose order with more than 32 elements due to optimizations in `immutable.js`. After `4.0.0-rc.5`, the `mergeDeepWith`-method is exported as a global export instead of being attatched to `Map`, and `List`. This PR uses the global export version `4.x` and uses the old way of merging for users with `3.x`. I also added a test with long arrays for immutable `setIn`. …

Immutable setIn is broken with more than 32 elements in an array.

---

src/ConnectedFieldArray.js
src/ConnectedFields.js
src/__tests__/FieldArray.spec.js
src/__tests__/FormSection.spec.js

This PR fixes the rest of #3755 that was introduced in `7.2.1` where nested async errors and submit errors are flat. The other change should have been released as `8.0.0` since this is a breaking change in how `asyncErrors` and `submitErrors` are handled by redux-form.
This PR should also fix #3779 
Note that this change requires errors for parent FieldArrays to be structured as `foo._error` when returned from the server. The tests should be clear as to what will happen.

Fix flat structure for asyncErrors and submitErrors for FieldArray and Fields.

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

This is a fix for an issue where the INITIALIZE action is fired twice, clearing change actions that happen when a form mounts.
See #3690 for details of the bug.
This fixes #3706 and fixes #3690.
I attempted to remove those formatting changes, but they got reversed by the precommit hook I believe.

Fix for double INITIALIZE happening on first mount

---

src/ConnectedField.js

Oops. #3755 should never have been merged.

Reverted breaking change in #3755

---

src/structure/immutable/__tests__/setIn.spec.js
src/structure/immutable/setIn.js

Turns out the list-merging was still broken in `7.2.2` since I hadnt bothered to test arrays with content in them already, `immutable.js@4.0.0-rc.5+` concats lists when merging them. This PR does the merging by hand instead of using a built in method to do it, and I added a test for it, so it shouldnt break in the future. I have tested this solution both with `immutable@3.8.2` and `immutable@4.0.0-rc.9`. Sorry for the broken PR that got merged in `7.2.2`.

Fix Immutable 4 merging. Again.

---

package.json

This adds the Webpack v4 sideEffects optimization. See a similar PR for Lodash: https://github.com/lodash/lodash/pull/3533
What does it do? If I import just one export from the library:
```
import { reducer } from 'redux-form'
```
then `sideEffects: false` ensures that only the reducer code and the code it depends on will be imported, and not all the reexports in `es/index.js`.
If the `sideEffects` flag were not set to `false`, Webpack must assume that the reexported modules can have side-effects (e.g., setting a property on `window`) and imports them all.
Very useful for code splitting where the main chunk typically imports only the reducer and the other chunks import UI components, selectors etc.

Add the Webpack 4 'sideEffects' flag

---

src/__tests__/reduxForm.spec.js
src/propTypes.js

Added propTypes for `clearFields` & `clearSubmitErrors` and test case comparing declared prop types in `src/propTypes.js` and passed to decorated component

Add clearFields and clearSubmitErrors to propTypes

---

docs/api/Selectors.md

Change names of keys to avoid colliding if one follows the naming of the documentation. 
Referring to issue #2899

Clarify sync and async keys in Documentation for selectors #2899 

---

docs/api/ActionCreators.md
src/__tests__/helpers/reducer.initialize.js
src/createReducer.js

I added the feature of #3649. Now I added just an option `keepValues`, but kept the initial values with the same flag. Should another flag `keepInitial` be set for this?

Feat: add keepValues to initialize (closes #3649)

---

src/createReducer.js

The Problem is that a successful validation triggered directly after an error does not get cleaned up correctly. The reason is that the asyncErrors field never gets cleared. This wasn't a problem in 6.x, but could easily be reproduced in 7.x. Simply go to https://redux-form.com/7.2.1/examples/asyncvalidation/ enter a password, go to the user field, enter john. No execute the following actions faster than one second:
1. press tab (going to password, triggering blur and validation)
1. press shift+tab (going back to user)
1. enter any letter (which will be a correct result in this example)
1. press tab again (triggering another blur and another validation which should be successful now)
The result should be that the error goes away once the second validation had been triggered (1-2 seconds …

Fix error in multiple async validation

---

src/handleSubmit.js

This reverts commit 1a0660c3477024c094f1906ddab0984a386a45f0 from #3723 
The rationale for this revert is explained in #3821 and #3801 
Closes #3821 
Closes #3801

Revert "fix: Log onSubmitSuccess thrown errors (#3723)"

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

When providing a custom `shouldError` prop, it needs to be passed into both `shouldError` and the deprecated `shouldValidate`.
```javascript
const customShouldError = () => { ... };
const myForm = reduxForm({
shouldError: customShouldError,
shouldValidate: customShouldError,
});
``` 
If only `shouldError` is passed in the `shouldValidate` may override the expected behavior.  For example the `shouldError` prop returns `false` but the default `shouldValidate` returns `true`, the code will still run the validation.
This PR will allow for either `shouldError` or `shouldValidate` to be used.

Use shouldError/shouldWarn by default unless only shouldValidate is passed in.

---

src/index.js.flow

Steps to reproduce:
1. Install `redux-form` 7.2.3
2. Install `flow-bin` 0.53
3. Try to import `clearFields` with Flow enabled:
```
// @flow
import {clearFields} from 'redux-form';
```
Expected: Flow does not error.
Actual: Flow displays the following error:
```
2: import {clearFields} from 'redux-form';
^^^^^^^^^^^ Named import from module `redux-form`. This module has no named export called `clearFields`.
```
This is because `index.js.flow` is missing declarations for `clearFields`.
This is my first time contributing to this repository - please let me know if there is anything else I need to do in order to get this PR accepted.

Fix: Update FlowType Definitions to include clearFields

---

examples/fieldLevelValidation/src/FieldLevelValidationForm.js
examples/immutable/src/warn.js

The current form of these tests is ageist and not something that I feel ought to be joked about. It would be a shame if anyone using this library came across this example and felt excluded or discriminated against as a result! 😞
This change switches the test to be a more common example: ensuring that an individual filling out a form meets a particular legal age requirement.

Update age test within examples

---

docs/api/Field.md
src/ConnectedField.js
src/ConnectedField.types.js.flow
src/FieldProps.types.js.flow
src/__tests__/Field.spec.js
src/createField.js

Add immutableProps option to Field component

---

src/actions.js
src/actions.types.js.flow

This makes the flow types consistent with the documentation.
Fixes #3668

Make optional arguments to initialize opional in flow

---

tools.md

This PR simply adds [`redux-form-input-masks`](https://github.com/renato-bohler/redux-form-input-masks) link to the `tools.md` file.
`redux-form-input-masks` is a library to easily create input masks for `redux-form`.

Tools: added redux-form-input-masks

---

package.json

For some reason, the good people at NPM decided that the 'prebublish' hook should also run on `npm install`, which I've always found to be unexpected. There is another hook though, `prepublishOnly` which _only_ runs on `npm publish` but not on `npm install`.
See [here](https://docs.npmjs.com/misc/scripts) for the relevant docs on npm scripts.

Use 'prebublishOnly' instead of 'prepublish'

---

src/createReduxForm.js

Because we do
```
return (
!structure.deepEqual(values, nextProps && nextProps.values) ||
!structure.deepEqual(lastFieldValidatorKeys, fieldValidatorKeys)
)
```
in the `defaultShouldValidate`, we have to remove the field keys from the `lastFieldValidatorKeys` when Field is destroyed, otherwise on re-mount the key still exists and validation is skipped.
Should fix:
https://github.com/erikras/redux-form/issues/3500
https://github.com/erikras/redux-form/issues/3566

Fix field not validating after re-mount (#3566, #3500)

---

docs/api/Selectors.md
src/selectors/__tests__/isDirty.spec.js
src/selectors/__tests__/isPristine.spec.js
src/selectors/isDirty.js
src/selectors/isDirty.types.js.flow
src/selectors/isPristine.js
src/selectors/isPristine.types.js.flow

Fields added for `isPristine` and `isDirty` selectors

---

src/__tests__/deleteInWithCleanUp.spec.js
src/__tests__/helpers/reducer.blur.js
src/createReducer.js
src/deleteInWithCleanUp.js

possibly fixes #2597  #3366 
@erikras What's your opinion here?
I will create an additional test to catch this case for the future.
Edit: Let me try to restructure it. I don't like to have this logic inside a util function. 
Edit2: The second commit did restructure the implementation. `deleteInWithCleanUp` now takes an optional `shouldDelete` function, where you can specify when to delete and when not.
Edit3: Added a test to the `BLUR` reducer, if you like it, I can add it also to the `CHANGE` and `CLEAR_FIELDS` reducer.

Dont delete initial initialValues structure on withCleanUp

---

src/FormSection.js

I have changed the propTypes of components props in FormSection so that the following bug can be resolved.
>FormSection propType doesn't allow React 16 Fragment #3859 
I want to contribute further. Looking forward to your comments and feedback. Do tell me if I have missed anything or code of conduct I needed to follow. Thank you.

Added proptype Proptypes.node to FormSection's component propTypes

---

docs/api/Selectors.md

Will save developers headache and wasted time on figuring this out via trial and error.
See: https://github.com/erikras/redux-form/issues/3768

docs: Add note that `formMeta` is populated lazily

---

package-lock.json
package.json

I have found the usage of `deep-equal` only in a test [here](https://github.com/krzysiek1507/redux-form/blob/03c37d7e19429e32e0d42810fe87ee69fe6cfab3/src/structure/immutable/__tests__/expectations.js#L2).

Move deep-equal to devDeps

---

examples/fieldLevelValidation/src/FieldLevelValidationForm.js

0 evaluates to false here, so you need to check for a number type. ;)

Fix type bug in field level validation example

---

src/FieldArrayProps.types.js.flow

With a stateless functional component passed as `component`, Flow cannot decide which type in the union to use. If we use a more specific type like `ElementType`, Flow can now figure out which case we mean.

Make it easier for Flow

---

docs/api/FormName.md
src/FormName.js
src/FormNameProps.types.js.flow
src/__tests__/FormName.spec.js
src/immutable.js
src/immutable.js.flow
src/index.js
src/index.js.flow
src/util/FormNameProps.types.js.flow.js

Based upon my suggestion in #4037

Create FormName render props component

---

src/ConnectedField.js
src/ConnectedFieldArray.js
src/ConnectedFields.js
src/createField.js
src/createFieldArray.js
src/createFields.js

I've created a higher-order component that makes it easy for custom form element components to consume `redux-form`'s `input` and `meta` props. I realized that for a couple of the form elements, I need to use [`React.forwardRef()`](https://reactjs.org/docs/forwarding-refs.html) in the HOC.
The ref-forwarding works as expected, but I get a couple prop type errors:
```
ERROR: 'Warning: Failed prop type: Invalid prop `component` supplied to `Field`.
ERROR: 'Warning: Failed prop type: Invalid prop `component` supplied to `ConnectedField`.
```
`React.forwardRef()` returns an object, not a function. `Field`'s `component` prop type is either `function` or `string`.
I borrowed the approach from https://github.com/erikras/redux-form/pull/3995. Now the `component` prop can be a `node` in …

Accept PropTypes.node for component props

---

src/createFieldArrayProps.js

The FieldArray's fields prop was missing the splice() function. This was once discussed in #2870.

Add missing splice() to FieldArray's fields prop

---

package-lock.json
package.json
src/Form.js
src/createField.js
src/createFieldArray.js
src/createFields.js
src/createReduxForm.js

Deepest apologies for the reckless release of `v7.4.0` without the [React 16.3 polyfill](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#open-source-project-maintainers).
Closes #4078 
Fixes #4069 
Fixes #4070 
Fixes #4072

Use react-lifecycles-compat polyfill

---

src/Form.js
src/createField.js
src/createFieldArray.js
src/createFields.js
src/createReduxForm.js

The addition of the `UNSAFE_` lifecycle methods broke React 15 compatibility. Those methods are not intended for libraries still supporting React 15. 
The only way to remove the React 16.4+ `StrictMode` warnings about `cWM`, `cWRP`, and `cWU` in a React 15 compatible way is to migrate these methods to the new lifecycle methods and use `react-lifecycles-compat` for backwards compatibility. The `UNSAFE_` methods were to support application authors with a known target version of React (16.3+) from having to migrate every component before upgrading. Unfortunately we can't do that trick. 
Since the automated tests are all run against React 16, I've confirmed this locally by building my fork, and copying the `lib` folder to `node_modules/redux-form` of a download of [this …

Hotfix: Revert all UNSAFE_ lifecycle methods

---

src/immutable.js
src/index.js

Fixes the requested changes of https://github.com/erikras/redux-form/pull/4040, as it seems to be inactive.
Closes #4040.

Export updateSyncErrors

---

examples/syncValidation/src/SyncValidation.md

While reading the sync validation page noticed that there is a typo. Just thought it would be somewhat useful to correct it.

Fix a small typo in SyncValidation doc

---

docs/faq/HandleVsOn.md

Per [this thread](https://github.com/erikras/redux-form/issues/4194), there's an extraneous `values` parameter that's unnecessary and confusing.

Docs: Remove extraneous `values`

---

src/index.js.flow

The getFormError selector takes in a form name but it was not accounted for in the Flow typedefs.
Also, the GetFormErrorInterface is not a polymorphic type.
See docs for this selector here:
https://redux-form.com/7.4.2/docs/api/selectors.md/

Fix getFormError Flow typedef.

---

src/handleSubmit.js

I didn't add any further tests for this change, just made sure existing ones pass. I can if you think it's needed.
FYI, CHANGELOG.md says to run `npm run format` but there's no such script in the package.

Made SubmissionError identification more flexible

---

src/ConnectedField.types.js.flow
src/ConnectedFieldArray.js
src/ConnectedFieldArray.types.js.flow
src/ConnectedFields.js
src/ConnectedFields.types.js.flow
src/FieldArrayProps.types.js.flow
src/FieldProps.types.js.flow
src/FieldsProps.types.js.flow
src/FormName.js
src/FormNameProps.types.js.flow
src/createReduxForm.js
src/immutable.js.flow
src/index.js.flow
src/util/FormNameProps.types.js.flow.js

This PR removes all `*` react imports, since React 15 is supported, when we import everything from React, we enter in a deprecated warning.
Fix #4083

Remove * imports to avoid warning in React 15

---

docs/api/Field.md
docs/api/Fields.md
docs/api/Props.md
docs/api/ReduxForm.md

This updates `Props.md` to use level 3 heading for all prop names. They were a mix of level 3 and level 4.
This also removes some extra `####` on `Field.md` and `Fields.md` and some leading dashes on the first two props of `ReduxForm.md`.

Docs: Improve props list

---

docs/ValueLifecycle.md

Values from lifecycle hooks can be of any type, not just string. I'm proposing to change the docs to account that.

Docs: Change value lifecycle types

---

docs/MigrationGuide.md
examples/material-ui/package.json
examples/material-ui/src/MaterialUiForm.js
examples/material-ui/src/index.js

This pull request resolve #3156
The material's documentation example uses an old version of material-ui.
I updated the version "material-ui" to the version 3.2.2

Material-ui example with the 3.2.2 version

---

src/ConnectedField.js
src/ConnectedFields.js

When I tried to pass component that that wrap `input['radio']` and add some styles I've got an issue with getting it checked(it doesn't work automatically until type `radio` is specified).
While digging into code I found [createFieldProps.js](https://github.com/erikras/redux-form/blob/e7ce5aec2bf0e24574e6f5f90bc04b9815c8e52e/src/createFieldProps.js) where `checked` prop calculates. Being curios where `_value` comes from I digged a bit more and found that line and it seems comments are misleading, since `_value` [is used](https://github.com/erikras/redux-form/blob/e7ce5aec2bf0e24574e6f5f90bc04b9815c8e52e/src/createFieldProps.js#L59) for `radio` not for `checkbox`

Fix misleading comment for _value

---

docs/api/Props.md
src/createReducer.js

function supported for `CHANGE`
e.g: `change(fieldName, (fieldValue, allValue) => {})`
```
this.props.change("data", preData => ({
...preData,
name: "hello world"
}));
```
@erikras PTAL

feat(change): function supported for change-action

---

examples/initializeFromState/src/InitializeFromStateForm.js

I was trying to help with this stackoverflow [question](https://stackoverflow.com/questions/51970636/how-to-display-initial-value-on-redux-form-date-input-field) where the user was struggling to initialize a `date` type Field and I thought adding it to the example might be helpful for others in the future. 
Here is it in action in a forked codesandbox: https://codesandbox.io/s/32n8221r21

Add example for initializing type date

---

src/createReduxForm.js

On reinitialize form it calls `onChange` method with previous initial values.
[Use `keepDirtyOnReinitialize={true}`](https://github.com/erikras/redux-form/issues/3729)
When initial values changed and reinitialize enabled:
```
// enableReinitialize(true) && initialized(true) && (!deepEqual(initialValues, stateInitial)) (true)
const shouldUpdateInitialValues = enableReinitialize && initialized && !deepEqual(initialValues, stateInitial)
// shouldUpdateInitialValues(true)
// initialValues (new initial values), stateInitial (previous initial values)
let initial = initialValues || stateInitial || empty
// initial (new initial values)
// if we should update initial values
if (shouldUpdateInitialValues) {
// we set old initial values as current values
initial = stateInitial || empty
}
// here at …
```

Fix form reinitialize problem: using previous initialValues

---

docs/api/Field.md

Updated the signature of validate and warning props as we can see it in the example section and in the propTypes of Field :
```js
// ...
validate: PropTypes.oneOfType([
PropTypes.func,
PropTypes.arrayOf(PropTypes.func)
]),
warn: PropTypes.oneOfType([
PropTypes.func,
PropTypes.arrayOf(PropTypes.func)
])
// ...
```

Field.md: Sync validate and warning signature

---

.babelrc.js

#4323 Fixed `.babelrc.js`. Prevent imports and exports processing if current `BABEL_ENV` is `es`.

Fix imports and exports in es-build (#4323)

---

docs/api/Fields.md
src/FieldsProps.types.js.flow
src/__tests__/Fields.spec.js
src/createFields.js

This changes add `Fields` level validation and warning.
`validate` and `warn` props can get an object or a function or an array with functions.
Example:
```jsx
<Fields
names={['facebook', 'twitter']}
component={FormSocials}
format={plainFormat}
validate={url}
/>
<Fields
names={['facebook', 'twitter']}
component={FormSocials}
format={plainFormat}
validate={{
facebook: url,
twitter: [required, url],
}}
/>
```

Fields validation

---

src/ConnectedField.js

Right now there's no way to cancel dispatching an event for React-Native.
Assign defaultPrevented to a returned value of the onChange callback for React-Native to prevent dispatching onChange/onFocus/onBlur for some cases.

A way to cancel dispatching events for RN.

---

src/ReduxFormContext.js

Our tests rely on component names and with special hoc additon that was broken. Nested components were named as Component. That fix restores original naming.

fix hoc displayName issue

---

README.md

Seems so that the relative link used for the contributors' image is linking to `blob/master/...`, which results in a 404 page. This absolute link should fix it.

Fix "Contributors" link

---

.babelrc.js
src/handleSubmit.js

This is a more general solution to #4313 because spread operators are used with immutable in several places in the project. Instead of fixing them all manually we can disable `loose` mode in `@babel/plugin-transform-spread`.
```
In loose mode, all iterables are assumed to be arrays.
```

disable loose mode for @babel/plugin-transform-spread

---

src/helpers.js
src/wrapMapDispatchToProps.js
src/wrapMapStateToProps.js

When using this version with the latest version of `reselect`, the props are not been passed to the  `mapStateToProps` selector generated by `createStructuredSelector` that the `form` HOC from redux-form takes for its second argument. The reason for that is that it does not accurately report its *arity*
as seen here
https://github.com/reduxjs/reselect/blob/master/src/index.js#L68.
This case is handled in the `react-redux` library  here
https://github.com/reduxjs/react-redux/blob/72ed6db1947913bdd4900b324243c43a490b4c5a/src/connect/wrapMapToProps.js#L22
I just copied it over and made sure we treat it the same way.

Improve detection of whether mapToProps functions depends on props.

---

src/structure/immutable/__tests__/deepEqual.spec.js
src/structure/immutable/deepEqual.js
src/structure/plain/__tests__/deepEqual.spec.js
src/structure/plain/deepEqual.js

Fixed incorrect deepEqual comparison for NaN -> 0 value change.
Issue: https://github.com/erikras/redux-form/issues/4378

Fixed deepEqual NaN -> 0 comparison 

---

docs/api/ReduxForm.md

* Add the missing description for case 'change' of the param 'trigger' in shouldAsyncValidate().

Docs: Add missing case 'change'

---

src/index.js.flow

FormProps should have referred to props passed by reduxForm() to wrapped components, but was instead referring to the props expected by the trivial <Form> component. This will cause new typechecking errors for people relying on the old behavior, but I suspect that is an uncommon use case.
Fixes #3823

FormProps export

---

src/createReduxForm.js

I have added a new excludeUnregistered option to getFieldsList() method which enables / disables the excluding of fields registered with zero reference.
I have also added to use this option in the submit(...) call.

Don't list and touch unregistered fields on submit

---

package-lock.json
package.json

Whatever script you are using to update the version strings when publishing a new release is doing too much @erikras 😄 
See https://github.com/erikras/redux-form/commit/3df8a6b3af431a7e32e8d4dd7fc3769e68fb537b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L120 for example.

Rollback versions that were changed to 8.2.0 by publish script

---

.babelrc.js
package.json
src/handleSubmit.js

Reverts erikras/redux-form#4337 since it cause a problem in FieldArray.
Closes #4439 #4456 #4457

Revert "disable loose mode for @babel/plugin-transform-spread"

---

src/FieldProps.types.js.flow

Components are like functions - contravariant in their arguments! Which
means we'd need to have a generic Props<PassthroughProps>, and somehow
would need to deal with the two prop-passthrough styles (though the
`props` prop and passed straight to the Field).
And who knows how well that would even type-infer.
Should fix #4434

FieldProps.types: Relax component type, document problem with strictness

---

.babelrc.js

Run tests using same babel config as built product. This was created in response to https://github.com/erikras/redux-form/issues/4439#issuecomment-496594691. The goal here is prove that ImmutableJS is now broken as of v8.2.1 via a set of tests which fail after #4337 was reverted by https://github.com/erikras/redux-form/pull/4466.
During investigation, I was going to write an immutable test that fails but instead I found that the babel configuration was incorrectly running with `{ targets: { node: '8' } }`. The test suite should run using the same target as the built product to eliminate scenarios where babel either fixes or introduces new issues in the built product that do not fail during testing. One can see that this branch / PR is failing the test suite due to ImmutableJS errors.

Run tests using same babel config as built product

---

.babelrc.js

Reverts erikras/redux-form#4470. This broke v8.2.2 and needs more examination.

Revert "Run tests using same babel config as built product"

---

src/handleSubmit.js

Reverts erikras/redux-form#4471. We can't `import from 'immutable'` in `handleSubmit`. We've got to abstract this out into something that gets passed in or lives in `structure`.
Fixes #4473.

Revert "Fix immutable support"

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

The `mapDispatchToProps` was only called once as it was returning a `() => computedActions` cached function. But in order to reflect a `form` property updates when one re-uses the decorated `reduxForm()(DetailComponent)` instance the bindings must be re-bound to the changed `form` prop value.

fix: re-bind actionCreators to changed props.form

---

package-lock.json
package.json
src/ReduxFormContext.js
src/__tests__/reduxFormContext.spec.js

Fix _reduxForm context rewrite

---

src/__tests__/reduxForm.spec.js
src/createReduxForm.js

`updateSyncWarningsIfNeeded` was using `syncWarnings` from `this.props`, but using it, in `componentWillReceiveProps` we won't have the value that we expected (since it's in `nextProps`), instead that, we use `lastSyncWarnings` that point for `nextProps`.
Closes #4488

Use lastSyncWarnings in updateSyncWarningsIfNeeded

---

src/__tests__/helpers/reducer.change.js
src/createReducer.js

fix(reducer/change): allow `change` to handle `undefined` payload

---

src/ConnectedFields.js
src/Form.js
src/__tests__/reduxForm.spec.js
src/createField.js
src/createFieldArray.js
src/createFields.js
src/createFormValues.js
src/createReduxForm.js

partialy resolves erikras/redux-form#4510
'UNSAFE_' prefixed methods shall work since react@16.3.0
https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-17
used `npx react-codemod rename-unsafe-lifecycles` command from _React v16.9.0 and the Roadmap Update_ https://reactjs.org/blog/2019/08/08/react-v16.9.0.html

chore: rename unsafe lifecycle methods to silence console warnings

---

package-lock.json
package.json

fixes vscode flow error
```
Flow version 0.72.0 doesn't support 'flow lsp'. Please upgrade flow to version >=0.75.
```
Closes #4336

fix(chore): upgrade flow-bin to maximum supported version

---

src/immutable.js
src/immutable.js.flow
src/index.js
src/index.js.flow

Pretty please 🍒 
fix #3852
`react-router` allows components to access the ancestor `<Route>` props from context by using `withRouter`;  Likewise `redux-form` should allow components to access the ancestor form props from context.
I have a component that needs to know know its enclosing `sectionPrefix` and dispatch `change` multiple fields under that `sectionPrefix`, and the public API (`formValueSelector`, custom `Field` components, action creators and selectors, etc) just doesn't cut it for this use case.

feat: export ReduxFormContext

---

src/__tests__/reduxForm.spec.js

By mistake I cherry picked a test and forgot to remove the `.only`. 
Fixing this.

reduxForm: remove .only from test

---

README.md

CodeFund sponsorships allow companies to sponsor GitHub projects and display their logo at the top of the README. For an example, see https://github.com/standard/standard

Add CodeFund Sponsorship

---

docs/api/Selectors.md

http://redux.js.org/docs/recipes/ComputingDerivedData.html is no longer accessible, and I believe that it has been moved to https://redux.js.org/recipes/computing-derived-data/ .

Fix a broken link in Selectors.md

---

src/ConnectedField.js

Fixes regression introduced in 8.1.0.
Issue #4309 adds a way to cancel dispatches from RN. However, the method
added also impacts React Web. This leads to a regression in React Web
due to application of RN behavior.
The current change locks the change from #4309 to RN, and maintains
existing behavior otherwise.
Related:
- #4391 outlines a case where this regression may cause problems. While
the issue mentions RN, this can easily occur outside RN as well.
- #4401 describes a similar issue and a user-end fix.
Closes #4391 
Closes #4401

fix(field): use onChange return as preventDefault only in RN

---

package.json

We're running `node scripts/*` in post-install, but scripts folder is ignored from npm, this generate an error at install.

Scripts - Fix postinstall

---

README.md
package-lock.json
package.json
src/createReduxForm.js
src/handleSubmit.js
src/structure/immutable/__tests__/expectations.js

`src/createReduxForm.js` -> `Form.getFieldList` should return a plain js array, but it returned in some cases an immutable `Seq`, that couldn't be spread in `handleSubmit`
Moved `immutable` to peer dependencies, because optional dependencies will install it always.
Related #4313
Related #4439
Related #4476
Related #4471
Related #4473
Related #4474
Closes #4519

fix: exclude immutable from handleSubmit and bundle

---

package-lock.json
package.json
src/Form.js
src/createField.js
src/createFieldArray.js
src/createFields.js
src/createReduxForm.js

As of `redux-form@8` major version, minimum `react@16.4` is required
New lifecycles methods were introduced in `react@16.3`
So `react-lifecycles-compat` is not required anymore
https://reactjs.org/blog/2018/03/29/react-v-16-3.html
https://github.com/redux-form/redux-form/releases/tag/v8.0.0
https://github.com/reactjs/react-lifecycles-compat

refactor: remove useless `react-lifecycles-compat`

---

src/immutable.js.flow

It seems the immutable flow action signatures are wrong. They were already fixed in the native JS version (index.js.flow), but immutable.js.flow was different. This pull request fixes the discrepancy.

fix: flow immutable js action creators

---

package.json
src/structure/immutable/__tests__/expectations.js
src/structure/plain/__tests__/expectations.js

https://jestjs.io/docs/en/expect#thisutils

chore: remove `jest-matcher-utils` in favor of jest `this.utils`

---

package-lock.json
package.json

this upgrade was fixed in 8x.
https://github.com/redux-form/redux-form/commit/d0053a0e99dce46c2d4eb6059866407e863c4100
but what about 7x? 
i cannot upgrade to 8x in this moment

fix: update lodash for redux-form@7 (CVE-2019-10744)

---

.size-limit.json
src/SubmissionError.js
src/__tests__/Form.spec.js
src/__tests__/SubmissionError.spec.js
src/__tests__/handleSubmit.spec.js
src/__tests__/reduxForm.spec.js
src/handleSubmit.js
src/immutable.js
src/index.js

Now event after obfuscation, or importing SubmissionForm
from a different context, `isSubmissionError` will return true
only for `SubmissionError`
Closes #4641

fix(v8): improve `SubmissionError` detection

---

package-lock.json
src/SubmissionError.js
src/__tests__/SubmissionError.spec.js
src/actions.js
src/handleSubmit.js

Now event after obfuscation, or importing SubmissionForm
from a different context, `isSubmissionError` will return true
only for `SubmissionError`
Closes #4092
Closes #4162

fix(v7): improve `SubmissionError` detection

---

src/Form.js

Closes #4682
When submiting form remotely by dispatching `submit` action and during `Form` lifetime and method provided to handleSubmit has changed - it isn't fired - only first function provided to `Form` is fired. After invastigation I've noticed that for remote submitting `submit` function from `createReduxForm.js` calls method `innerOnSubmit()` and it is set with following function: `registerInnerOnSubmit: innerOnSubmit => (this.innerOnSubmit = innerOnSubmit)`. 
In `Form.js` I can see that it only register method when component will mount ` this.props._reduxForm.registerInnerOnSubmit(this.props.onSubmit)` so even if you change method provided to handleSubmit during `Form` life, it wont be fired `onSubmit`. 
My fix adds possibility to change that method during `Form` life.

Add possibility to change function passed to handleSubmit

---

package.json

Related tweet 
https://twitter.com/wesbos/status/1359173446740172810
Fixes Could not resolve dependency:
peer react@"^16.4.2" from redux-form@8.3.7
https://github.com/redux-form/redux-form/issues/4721
and 
https://github.com/redux-form/redux-form/issues/4710

Fix peer dependency for react 17.0.x

---

package.json
src/util/isHotReloading.js

This PR fixes a significant regression in `redux-form` v8.1.0 (and above), where the following error is thrown in the browser on any page using `redux-form`:
```
Uncaught ReferenceError: module is not defined
```
I fixed it by ensuring that the `module` reference is guarded by `typeof`.
Note that I also updated package.json to use an npm `prepare` script instead of `prepublishOnly`, because that allows me to use my GitHub fork as a dependency in my app. I think it would be a good idea to use `prepare`, but I'm happy to revert that commit if you'd prefer, as it's unrelated to the bugfix.

Avoid assuming that module exists
